import {test as base,expect} from './fixtures/bean'

const test=base.extend<{}, {appName:string}>({appName:['asana',{scope:'worker'}]})

test('anonymous local project uses board, deep subtasks, and attachments',async({page,request,bean})=>{
  await page.setViewportSize({width:500,height:800})
  await page.goto(bean.baseURL+'/')
  await expect(page.getByRole('heading',{name:'Asana Lite'})).toBeVisible()
  await expect(page.getByRole('link',{name:'Sign in'})).toHaveCount(0)
  const panels=page.locator('section[data-component="Page"] > section[data-component="Panel"]')
  const tracks=(index:number)=>panels.nth(index).evaluate(element=>getComputedStyle(element).gridTemplateColumns.split(' ').filter(Boolean).length)
  await expect(panels).toHaveCount(2)
  await expect(panels.nth(0)).toHaveAttribute('data-layout','single-column')
  await expect(panels.nth(1)).toHaveAttribute('data-layout','two-column')
  expect(await tracks(1)).toBe(1)
  await page.setViewportSize({width:800,height:800})
  expect(await tracks(1)).toBe(2)

  await page.getByLabel('name').fill('Local launch')
  await page.getByLabel('description').fill('Ship the local app')
  await page.getByRole('button',{name:'Submit'}).click()
  await expect(page.getByText('Project created. Refresh to open it.')).toBeVisible()
  await page.reload()
  const projectLink=page.getByRole('link',{name:'Local launch'})
  const projectPath=await projectLink.getAttribute('href')
  await projectLink.click()
  await expect(panels).toHaveCount(4)
  await expect(panels.nth(0)).toHaveAttribute('data-layout','single-column')
  await expect(panels.nth(1)).toHaveAttribute('data-layout','two-column')
  await expect(panels.nth(2)).toHaveAttribute('data-layout','single-column')
  await expect(panels.nth(3)).toHaveAttribute('data-layout','single-column')
  await expect(page.getByRole('heading',{name:'Tasks by status'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'Root task board'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'Full task hierarchy'})).toBeVisible()

  await page.getByLabel('title').fill('Build release')
  await page.getByLabel('description').fill('Prepare the alpha')
  await page.getByLabel('priority',{exact:true}).selectOption('high')
  await page.getByRole('button',{name:'Submit'}).click()
  await expect(page.getByText('Task created. Refresh the project to see it.')).toBeVisible()
  await page.reload()

  const rootLink=page.getByRole('link',{name:'Build release'}).first()
  const rootPath=await rootLink.getAttribute('href')
  const status=page.getByRole('combobox',{name:'Status for Build release'})
  await status.selectOption('in_progress')
  await expect(status).toHaveValue('in_progress')
  await rootLink.click()
  await expect(page).toHaveURL(bean.baseURL+rootPath)
  await expect(panels).toHaveCount(3)
  await expect(panels.nth(0)).toHaveAttribute('data-layout','single-column')
  await expect(panels.nth(1)).toHaveAttribute('data-layout','two-column')
  await expect(panels.nth(2)).toHaveAttribute('data-layout','single-column')
  await expect(page.getByText('Add a subtask to create the next hierarchy level, or upload one or more small attachments.')).toBeVisible()
  await expect(page.getByRole('heading',{name:'Add a subtask'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'Upload an attachment'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'Attachments'})).toBeVisible()

  await page.getByLabel('title').fill('Write migration notes')
  await page.getByLabel('description').fill('Document upgrade steps')
  await page.getByLabel('priority').selectOption('medium')
  await page.getByRole('button',{name:'Submit'}).first().click()
  await expect(page.getByText('Subtask created. Open the project tree to see the full hierarchy.')).toBeVisible()
  await page.goto(bean.baseURL+projectPath)
  const childLink=page.getByRole('link',{name:'Write migration notes'})
  await expect(childLink).toBeVisible()
  const childPath=await childLink.getAttribute('href')
  await childLink.click()
  await expect(page).toHaveURL(bean.baseURL+childPath)
  await expect(page.getByText('Add a subtask to create the next hierarchy level, or upload one or more small attachments.')).toBeVisible()

  await page.getByLabel('title').fill('Check examples')
  await page.getByLabel('priority').selectOption('low')
  await page.getByRole('button',{name:'Submit'}).first().click()
  await page.goto(bean.baseURL+projectPath)
  await expect(page.getByTestId('tree-view').getByRole('link',{name:'Check examples'})).toBeVisible()

  await page.goto(bean.baseURL+rootPath)
  await page.getByLabel('label').fill('Release plan')
  await page.getByLabel('file').setInputFiles({name:'plan.txt',mimeType:'text/plain',buffer:Buffer.from('Asana Lite plan')})
  await page.getByRole('button',{name:'Submit'}).last().click()
  await expect(page.getByText('Attachment uploaded.')).toBeVisible()
  await page.reload()
  const download=page.getByRole('link',{name:'Download attachment'})
  const href=await download.getAttribute('href')
  const response=await request.get(bean.baseURL+href)
  expect(response.ok()).toBeTruthy()
  expect(await response.text()).toBe('Asana Lite plan')
})
