import {test as base,expect} from './fixtures/bean'
import {login} from './fixtures/bean'

const test=base.extend<{}, {appName:string}>({appName:['ats',{scope:'worker'}]})

test('applicant tracker opens populated and operational',async({page,bean})=>{
  await page.goto(bean.baseURL+'/')
  await expect(page.getByRole('link',{name:'Acme Recruiting'})).toBeVisible()
  await expect(page.getByTestId('application-shell')).toHaveAttribute('data-accent','indigo')
  await expect(page.getByTestId('metric-value')).toHaveText('12')
  await expect(page.getByTestId('timeline-view')).toBeVisible()

  await page.getByRole('searchbox',{name:'Search candidate records'}).first().fill('Avery')
  await page.getByRole('button',{name:'Search'}).first().click()
  await expect(page.getByRole('link',{name:'Avery Nguyen 1',exact:true}).first()).toBeVisible()

  const status=page.getByRole('combobox',{name:'Status for Avery Nguyen 1',exact:true})
  await status.selectOption('screen')
  await expect(status).toHaveValue('screen')

  await page.getByRole('link',{name:'Avery Nguyen 1',exact:true}).first().click()
  await expect(page).toHaveURL(/\/candidates\//)
  await expect(page.getByRole('heading',{name:'Avery Nguyen 1',exact:true})).toBeVisible()
  const candidateID=page.url().split('/').at(-1)!

  await page.getByRole('link',{name:'Candidates',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Candidates',level:1})).toBeVisible()
  await expect(page.getByRole('columnheader',{name:'Candidate'})).toBeVisible()
  await expect(page.getByRole('button',{name:'Next'})).toBeDisabled()
  await expect(page.getByRole('button',{name:'Previous'})).toBeDisabled()
  await page.getByRole('combobox',{name:'Stage'}).selectOption('screen')
  await page.getByRole('button',{name:'Apply'}).click()
  await expect(page).toHaveURL(/stage=screen/)
  await expect(page.getByRole('cell',{name:'screen'}).first()).toBeVisible()

  const coldOnboardingStarted=Date.now()
  await login(page,bean.baseURL)
  await page.goto(bean.baseURL+'/admin/candidate/'+candidateID)
  const applied=page.getByTestId('field-applied_at')
  await expect(applied).not.toHaveValue('')
  expect(await applied.evaluate((element:HTMLInputElement)=>element.validity.valid)).toBe(true)
  expect(new Date(await applied.inputValue()).toISOString()).toBe('2026-01-01T09:00:00.000Z')
  await page.getByTestId('field-summary').fill('Verified through the Admin edit form.')
  await page.getByTestId('save-candidate').click()
  await expect(page).toHaveURL(bean.baseURL+'/admin/candidate')
  await page.getByRole('link',{name:'Avery Nguyen 1',exact:true}).click()
  await page.reload()
  await expect(page.getByTestId('field-summary')).toHaveValue('Verified through the Admin edit form.')
  expect(new Date(await applied.inputValue()).toISOString()).toBe('2026-01-01T09:00:00.000Z')
  await page.goto(bean.baseURL+'/explore')
  await page.getByTestId('explore-entity').selectOption('candidate')
  await page.getByTestId('explore-name').fill('candidate_follow_up')
  await page.getByLabel('Page route (optional)').fill('/candidate-follow-up')
  await page.getByLabel('Filter field').selectOption('stage')
  await page.getByLabel('Filter value').fill('interview')
  await page.getByTestId('explore-preview').click()
  await expect(page.getByRole('cell',{name:'interview'}).first()).toBeVisible()
  await page.getByTestId('explore-save').click()
  await expect(page.getByText('Saved View candidate_follow_up to the deterministic Studio draft.')).toBeVisible()
  await expect(page.getByText(/Draft validates\. Semantic changes:/)).toBeVisible()
  await page.goto(bean.baseURL+'/studio')
  await page.getByTestId('validate-release').click()
  await expect(page.getByText('No schema changes.')).toBeVisible()
  await page.getByTestId('publish-release').click()
  await expect(page.getByTestId('diagnostics')).toContainText('"status": "active"')
  await page.goto(bean.baseURL+'/candidate-follow-up')
  await expect(page.getByRole('heading',{name:'Candidate'})).toBeVisible()
  await expect(page.getByRole('cell',{name:'interview'}).first()).toBeVisible()
  const coldOnboardingMs=Date.now()-coldOnboardingStarted

  const onboardingStarted=Date.now()
  await page.goto(bean.baseURL+'/explore')
  await page.getByTestId('explore-entity').selectOption('candidate')
  await page.getByTestId('explore-name').fill('candidate_stage_snapshot')
  await page.getByLabel('Result').selectOption('groups')
  await page.getByLabel('Group field').selectOption('stage')
  await page.getByLabel('Page route (optional)').fill('/candidate-stage-snapshot')
  await page.getByTestId('explore-preview').click()
  await expect(page.getByRole('columnheader',{name:'Total'})).toBeVisible()
  await page.getByTestId('explore-save').click()
  await expect(page.getByText('Saved View candidate_stage_snapshot to the deterministic Studio draft.')).toBeVisible()
  await page.goto(bean.baseURL+'/studio')
  await page.getByTestId('validate-release').click()
  await expect(page.getByText('No schema changes.')).toBeVisible()
  await page.getByTestId('publish-release').click()
  await expect(page.getByTestId('diagnostics')).toContainText('"status": "active"')
  await page.goto(bean.baseURL+'/candidate-stage-snapshot')
  await expect(page.getByTestId('bar-chart')).toBeVisible()
  const warmOnboardingMs=Date.now()-onboardingStarted
  console.log(`Explore onboarding benchmark: cold=${coldOnboardingMs}ms warm=${warmOnboardingMs}ms humanInterventions=0`)
  expect(coldOnboardingMs).toBeLessThan(300_000)
  expect(warmOnboardingMs).toBeLessThan(300_000)
})
