import type {Locator} from '@playwright/test'
import {test as base,expect,login} from './fixtures/bean'

const test=base.extend<{}, {appName:string}>({appName:['blog',{scope:'worker'}]})

test('complete blog editorial, identity, and moderation journey',async({page,bean},testInfo)=>{
  await page.setViewportSize({width:1100,height:900})
  const panels=page.locator('section[data-component="Page"] > section[data-component="Panel"]')
  const tracks=(panel:Locator)=>panel.evaluate(element=>getComputedStyle(element).gridTemplateColumns.split(' ').filter(Boolean).length)
  await login(page,bean.baseURL,'editor@example.test','test-password')
  await expect(page.getByRole('heading',{name:'Administration'})).toBeVisible()
  await expect(page.getByRole('link',{name:'System'})).toHaveCount(0)

  await page.evaluate(()=>sessionStorage.removeItem('bean_csrf'))
  await page.reload()
  await expect(page.getByRole('heading',{name:'Administration'})).toBeVisible()

  await page.getByRole('link',{name:/Category/}).click()
  await page.getByRole('link',{name:'Add Category'}).click()
  await page.getByTestId('field-name').fill('Engineering')
  await page.getByTestId('field-slug').fill('engineering')
  await page.getByTestId('create-category').click()
  await page.getByRole('link',{name:'Administration'}).click()

  for(const [name,slug] of [['Go','go'],['Runtime','runtime']]){
    await page.getByRole('link',{name:/Tag/}).click()
    await page.getByRole('link',{name:'Add Tag'}).click()
    await page.getByTestId('field-name').fill(name)
    await page.getByTestId('field-slug').fill(slug)
    await page.getByTestId('create-tag').click()
    await page.getByRole('link',{name:'Administration'}).click()
  }

  async function createPost(title:string,slug:string,body:string){
    await page.goto(bean.baseURL+'/admin/post/new')
    await expect(page.getByRole('group',{name:'Content',exact:true})).toBeVisible()
    for(const width of [390,800,1100]){
      await page.setViewportSize({width,height:900})
      const titleField=page.locator('[data-layout-field="title"]')
      const slugField=page.locator('[data-layout-field="slug"]')
      const bodyField=page.locator('[data-layout-field="body"]')
      const titleBox=await titleField.boundingBox();const slugBox=await slugField.boundingBox();const bodyBox=await bodyField.boundingBox()
      expect(titleBox&&slugBox&&bodyBox).toBeTruthy()
      if(width<768){expect(slugBox!.y).toBeGreaterThan(titleBox!.y);expect(Math.abs(bodyBox!.width-titleBox!.width)).toBeLessThan(2)}
      else{expect(Math.abs(slugBox!.y-titleBox!.y)).toBeLessThan(2);expect(bodyBox!.width).toBeGreaterThan(titleBox!.width*1.9)}
      expect(await page.locator('[data-testid="field-layout"] [data-layout-field]').evaluateAll(fields=>fields.map(field=>field.getAttribute('data-layout-field')))).toEqual(['title','slug','excerpt','body','author_display_name','category_id','tags'])
      expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
    }
    await page.getByTestId('field-title').focus()
    for(const name of ['slug','excerpt','body']){await page.keyboard.press('Tab');await expect(page.getByTestId('field-'+name)).toBeFocused()}
    await page.getByTestId('field-title').fill(title)
    await page.getByTestId('field-slug').fill(slug)
    await page.getByTestId('field-excerpt').fill('A complete vertical slice')
    await page.getByTestId('field-body').fill(body)
    await page.getByTestId('field-author_display_name').fill('Editor')
    await page.getByTestId('field-category_id').selectOption({label:'Engineering'})
    await page.getByTestId('field-tags').selectOption([{label:'Go'},{label:'Runtime'}])
    await expect(page.getByTestId('field-status')).toHaveCount(0)
    if(slug==='bean-ships'){
      await page.screenshot({path:testInfo.outputPath('grouped-form-light.png'),fullPage:true,animations:'disabled'})
      await page.getByRole('button',{name:'Use dark theme'}).click()
      await page.screenshot({path:testInfo.outputPath('grouped-form-dark.png'),fullPage:true,animations:'disabled'})
      await page.setViewportSize({width:390,height:900})
      await page.getByTestId('field-body').fill(body+'\n\n'+'unbrokentext'.repeat(200))
      expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
      await page.getByTestId('field-body').fill(body)
      await page.evaluate(()=>window.scrollTo(0,0))
      await page.screenshot({path:testInfo.outputPath('grouped-form-mobile.png'),fullPage:true,animations:'disabled'})
      await page.getByRole('button',{name:'Use light theme'}).click()
      await page.setViewportSize({width:1100,height:900})
    }
    await page.getByTestId('create-post').click()
    await expect(page.getByRole('heading',{name:title})).toBeVisible()
    return page.url().split('/').at(-1)!
  }
  const postID=await createPost('Bean ships','bean-ships','## Safe **Markdown body**.\n\n<script>window.pwned=true</script>\n\n[bad](javascript:alert(1))')
  await page.getByTestId('field-excerpt').fill('An edited vertical slice')
  await page.getByTestId('save-post').click()
  await expect(page).toHaveURL(bean.baseURL+'/admin/post')
  await page.goto(bean.baseURL+'/admin/post/'+postID)
  await expect(page.getByTestId('field-excerpt')).toHaveValue('An edited vertical slice')
  await page.reload()
  await expect(page.getByRole('group',{name:'Classification'})).toBeVisible()
  await expect(page.getByTestId('field-excerpt')).toHaveValue('An edited vertical slice')
  await page.goto(bean.baseURL+'/posts/bean-ships/record')
  await expect(page.getByText('Bean ships')).toHaveCount(0)

  await page.goto(bean.baseURL+'/')
  await expect(page.getByText('Bean ships')).toHaveCount(0)
  await page.goto(bean.baseURL+'/posts/bean-ships')
  await expect(page.getByText('Bean ships')).toHaveCount(0)
  for(const path of ['/api/blog/posts','/rss.xml','/api/views/published_posts_by_category?category_slug=engineering','/api/views/published_posts_by_tag?tag_slug=go']){
    expect(await (await page.request.get(bean.baseURL+path)).text()).not.toContain('Bean ships')
  }

  await page.goto(bean.baseURL+'/admin/post')
  await page.getByRole('link',{name:/Bean ships/}).click()
  await page.getByRole('button',{name:'Run for 1'}).click()
  await page.getByRole('button',{name:'Confirm action'}).click()
  await expect(page.getByRole('status')).toContainText('Action completed')
  await expect(page.locator('.history').getByText('Publish post')).toBeVisible()
  await page.goto(bean.baseURL+'/posts/bean-ships')
  await expect(page.getByText('Bean ships')).toBeVisible()
  await expect(page).toHaveTitle('Post')
  await expect(panels).toHaveCount(2)
  await expect(panels.nth(0)).toHaveAttribute('data-page-width','contained')
  await expect(panels.nth(1)).toHaveAttribute('data-page-width','wide')
  await expect(panels.nth(1)).toHaveAttribute('data-layout','main-sidebar')
  const discussionRegions=panels.nth(1).locator(':scope > section[data-component="Region"]')
  await expect(discussionRegions).toHaveCount(2)
  expect(await discussionRegions.evaluateAll(regions=>regions.map(region=>region.getAttribute('data-region')))).toEqual(['main','sidebar'])
  await expect(page.getByRole('heading',{name:'Discussion',exact:true})).toBeVisible()
  await expect(page.getByRole('heading',{name:'Join the discussion'})).toBeVisible()
  expect(await tracks(panels.nth(1))).toBe(3)
  await page.setViewportSize({width:500,height:900})
  expect(await tracks(panels.nth(1))).toBe(1)
  expect(await discussionRegions.evaluateAll(regions=>regions.map(region=>region.getAttribute('data-region')))).toEqual(['main','sidebar'])
  await page.setViewportSize({width:1100,height:900})
  await expect(page.getByText('Engineering')).toBeVisible()
  await expect(page.getByText(/Go, Runtime|Runtime, Go/)).toBeVisible()
  await expect(page.locator('.rich-text strong')).toHaveText('Markdown body')
  await expect(page.locator('.rich-text script')).toHaveCount(0)
  await expect(page.locator('.rich-text a[href^="javascript:"]')).toHaveCount(0)
  expect(await (await page.request.get(bean.baseURL+'/rss.xml')).text()).toContain('Bean ships')
  await page.goto(bean.baseURL+'/posts/bean-ships/record')
  await expect(page.getByRole('heading',{name:'Bean ships',exact:true})).toBeVisible()
  await expect(page.getByRole('region',{name:'Publication'})).toBeVisible()
  await page.screenshot({path:testInfo.outputPath('grouped-detail.png'),fullPage:true,animations:'disabled'})
  await expect(page.getByRole('region',{name:'Content',exact:true})).toContainText('An edited vertical slice')
  await expect(page.locator('.rich-text strong')).toHaveText('Markdown body')
  await expect(page.locator('.rich-text script')).toHaveCount(0)
  await expect(page.locator('.rich-text a[href^="javascript:"]')).toHaveCount(0)
  for(const width of [390,800,1100]){
    await page.setViewportSize({width,height:900})
    const grid=page.getByRole('region',{name:'Publication'}).locator('dl')
    expect(await tracks(grid)).toBe(width<768?1:2)
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  }
  await page.reload()
  await expect(page.getByRole('region',{name:'Content',exact:true})).toContainText('An edited vertical slice')

  const otherPostID=await createPost('Other post','other-post','Other post body.')
  await page.getByRole('button',{name:'Run for 1'}).click()
  await page.getByRole('button',{name:'Confirm action'}).click()
  await expect(page.getByRole('status')).toContainText('Action completed')

  await page.getByRole('button',{name:'Sign out'}).click()
  await page.goto(bean.baseURL+'/signup')
  await expect(panels).toHaveCount(1)
  await expect(panels.first()).toHaveAttribute('data-page-width','contained')
  await page.getByLabel('display name').fill('Ada Member')
  await page.getByLabel('email').fill('ada@example.test')
  await page.getByLabel('password',{exact:true}).fill('member-password')
  await page.getByLabel('password confirmation').fill('member-password')
  await page.getByRole('button',{name:'Submit'}).click()
  await expect(page.getByRole('status')).toContainText('Account created')
  await login(page,bean.baseURL,'ada@example.test','member-password',/\/$/)
  await expect(page.getByRole('link',{name:'Admin'})).toHaveCount(0)
  await expect(page.getByRole('link',{name:'Studio'})).toHaveCount(0)

  await page.goto(bean.baseURL+'/posts/bean-ships')
  await page.getByLabel('body').fill('Thoughtful member comment')
  await page.getByRole('button',{name:'Submit'}).click()
  await expect(page.getByRole('status')).toContainText('awaiting approval')
  await page.goto(bean.baseURL+'/posts/other-post')
  await page.getByLabel('body').fill('Other post comment')
  await page.getByRole('button',{name:'Submit'}).click()
  await expect(page.getByRole('status')).toContainText('awaiting approval')
  await page.goto(bean.baseURL+'/blog/'+postID+'/comments')
  await expect(page.getByText('Thoughtful member comment')).toHaveCount(0)
  await page.getByRole('button',{name:'Sign out'}).click()
  await page.goto(bean.baseURL+'/posts/bean-ships')
  await expect(page.getByText('Thoughtful member comment')).toHaveCount(0)

  await login(page,bean.baseURL,'editor@example.test','test-password')
  await page.goto(bean.baseURL+'/blog/'+postID+'/comments')
  await expect(panels).toHaveCount(1)
  await expect(panels.first()).toHaveAttribute('data-page-width','wide')
  await expect(page.getByRole('heading',{name:'Comment',exact:true})).toBeVisible()
  await expect(page.getByLabel('Status')).toHaveValue('pending')
  await expect(page.getByText('Thoughtful member comment')).toBeVisible()
  await expect(page.getByText('Other post comment')).toHaveCount(0)
  await page.getByRole('checkbox',{name:'Select Ada Member'}).check()
  await page.getByRole('button',{name:'Run for 1'}).click()
  await page.getByRole('button',{name:'Confirm action'}).click()
  await expect(page.getByText('Thoughtful member comment')).toHaveCount(0)
  await page.getByLabel('Status').selectOption('approved')
  await expect(page.getByText('Thoughtful member comment')).toBeVisible()
  await page.goto(bean.baseURL+'/blog/'+otherPostID+'/comments')
  await expect(page.getByText('Other post comment')).toBeVisible()
  await expect(page.getByText('Thoughtful member comment')).toHaveCount(0)
  await page.goto(bean.baseURL+'/posts/bean-ships')
  await expect(page.getByText('Thoughtful member comment')).toBeVisible()
  await page.getByRole('button',{name:'Sign out'}).click()
  await expect(page.getByRole('link',{name:'Admin'})).toHaveCount(0)
  await expect(page.getByText('Thoughtful member comment')).toBeVisible()
  await expect(panels).toHaveCount(2)
  const anonymousDiscussion=panels.nth(1)
  await expect(anonymousDiscussion).toHaveAttribute('data-page-width','wide')
  const anonymousRegions=anonymousDiscussion.locator(':scope > section[data-component="Region"]')
  await expect(anonymousRegions).toHaveCount(1)
  await expect(anonymousRegions.first()).toHaveAttribute('data-region','main')
  await expect(anonymousRegions.first()).toHaveAttribute('data-expanded','true')
  await expect(page.getByRole('heading',{name:'Join the discussion'})).toHaveCount(0)
})
