import {test as base,expect,login} from './fixtures/bean'

const test=base.extend<{}, {appName:string}>({appName:['blog',{scope:'worker'}]})

test('complete blog editorial, identity, and moderation journey',async({page,bean})=>{
  await login(page,bean.baseURL,'editor@example.test','test-password')
  await expect(page.getByRole('heading',{name:'Administration'})).toBeVisible()
  await expect(page.getByRole('link',{name:'System'})).toHaveCount(0)

  await page.getByRole('link',{name:/Category/}).click()
  await page.getByRole('link',{name:'Add Category'}).click()
  await page.getByTestId('field-name').fill('Engineering')
  await page.getByTestId('field-slug').fill('engineering')
  await page.getByTestId('create-category').click()
  await page.getByRole('link',{name:'Administration'}).click()

  for(const [name,slug] of [['Go','go'],['Runtime','runtime']]){
    await page.getByRole('link',{name:/Tag/}).click()
    await page.getByRole('link',{name:'Add Tag'}).click()
    await page.getByTestId('field-name').fill(name)
    await page.getByTestId('field-slug').fill(slug)
    await page.getByTestId('create-tag').click()
    await page.getByRole('link',{name:'Administration'}).click()
  }

  async function createPost(title:string,slug:string,body:string){
    await page.goto(bean.baseURL+'/admin/post/new')
    await page.getByTestId('field-title').fill(title)
    await page.getByTestId('field-slug').fill(slug)
    await page.getByTestId('field-excerpt').fill('A complete vertical slice')
    await page.getByTestId('field-body').fill(body)
    await page.getByTestId('field-author_display_name').fill('Editor')
    await page.getByTestId('field-category_id').selectOption({label:'Engineering'})
    await page.getByTestId('field-tags').selectOption([{label:'Go'},{label:'Runtime'}])
    await expect(page.getByTestId('field-status')).toHaveCount(0)
    await page.getByTestId('create-post').click()
    await expect(page.getByRole('heading',{name:title})).toBeVisible()
    return page.url().split('/').at(-1)!
  }
  const postID=await createPost('Bean ships','bean-ships','## Safe **Markdown body**.\n\n<script>window.pwned=true</script>\n\n[bad](javascript:alert(1))')

  await page.goto(bean.baseURL+'/')
  await expect(page.getByText('Bean ships')).toHaveCount(0)
  await page.goto(bean.baseURL+'/posts/bean-ships')
  await expect(page.getByText('Bean ships')).toHaveCount(0)
  for(const path of ['/api/blog/posts','/rss.xml','/api/views/published_posts_by_category?category_slug=engineering','/api/views/published_posts_by_tag?tag_slug=go']){
    expect(await (await page.request.get(bean.baseURL+path)).text()).not.toContain('Bean ships')
  }

  await page.goto(bean.baseURL+'/admin/post')
  await page.getByRole('link',{name:/Bean ships/}).click()
  await page.getByRole('button',{name:'Run for 1'}).click()
  await page.getByRole('button',{name:'Confirm action'}).click()
  await expect(page.getByRole('status')).toContainText('Action completed')
  await expect(page.locator('.history').getByText('Publish post')).toBeVisible()
  await page.goto(bean.baseURL+'/posts/bean-ships')
  await expect(page.getByText('Bean ships')).toBeVisible()
  await expect(page).toHaveTitle('Post')
  await expect(page.getByText('Engineering')).toBeVisible()
  await expect(page.getByText(/Go, Runtime|Runtime, Go/)).toBeVisible()
  await expect(page.locator('.rich-text strong')).toHaveText('Markdown body')
  await expect(page.locator('.rich-text script')).toHaveCount(0)
  await expect(page.locator('.rich-text a[href^="javascript:"]')).toHaveCount(0)
  expect(await (await page.request.get(bean.baseURL+'/rss.xml')).text()).toContain('Bean ships')

  const otherPostID=await createPost('Other post','other-post','Other post body.')
  await page.getByRole('button',{name:'Run for 1'}).click()
  await page.getByRole('button',{name:'Confirm action'}).click()
  await expect(page.getByRole('status')).toContainText('Action completed')

  await page.getByRole('button',{name:'Sign out'}).click()
  await page.goto(bean.baseURL+'/signup')
  await page.getByLabel('display name').fill('Ada Member')
  await page.getByLabel('email').fill('ada@example.test')
  await page.getByLabel('password',{exact:true}).fill('member-password')
  await page.getByLabel('password confirmation').fill('member-password')
  await page.getByRole('button',{name:'Submit'}).click()
  await expect(page.getByRole('status')).toContainText('Account created')
  await login(page,bean.baseURL,'ada@example.test','member-password',/\/$/)
  await expect(page.getByRole('link',{name:'Admin'})).toHaveCount(0)
  await expect(page.getByRole('link',{name:'Studio'})).toHaveCount(0)

  await page.goto(bean.baseURL+'/posts/bean-ships')
  await page.getByLabel('body').fill('Thoughtful member comment')
  await page.getByRole('button',{name:'Submit'}).click()
  await expect(page.getByRole('status')).toContainText('awaiting approval')
  await page.goto(bean.baseURL+'/posts/other-post')
  await page.getByLabel('body').fill('Other post comment')
  await page.getByRole('button',{name:'Submit'}).click()
  await expect(page.getByRole('status')).toContainText('awaiting approval')
  await page.goto(bean.baseURL+'/blog/'+postID+'/comments')
  await expect(page.getByText('Thoughtful member comment')).toHaveCount(0)
  await page.getByRole('button',{name:'Sign out'}).click()
  await page.goto(bean.baseURL+'/posts/bean-ships')
  await expect(page.getByText('Thoughtful member comment')).toHaveCount(0)

  await login(page,bean.baseURL,'editor@example.test','test-password')
  await page.goto(bean.baseURL+'/blog/'+postID+'/comments')
  await expect(page.getByRole('heading',{name:'Comment',exact:true})).toBeVisible()
  await expect(page.getByLabel('Status')).toHaveValue('pending')
  await expect(page.getByText('Thoughtful member comment')).toBeVisible()
  await expect(page.getByText('Other post comment')).toHaveCount(0)
  await page.getByRole('checkbox',{name:'Select Ada Member'}).check()
  await page.getByRole('button',{name:'Run for 1'}).click()
  await page.getByRole('button',{name:'Confirm action'}).click()
  await expect(page.getByText('Thoughtful member comment')).toHaveCount(0)
  await page.getByLabel('Status').selectOption('approved')
  await expect(page.getByText('Thoughtful member comment')).toBeVisible()
  await page.goto(bean.baseURL+'/blog/'+otherPostID+'/comments')
  await expect(page.getByText('Other post comment')).toBeVisible()
  await expect(page.getByText('Thoughtful member comment')).toHaveCount(0)
  await page.goto(bean.baseURL+'/posts/bean-ships')
  await expect(page.getByText('Thoughtful member comment')).toBeVisible()
  await page.getByRole('button',{name:'Sign out'}).click()
  await expect(page.getByRole('link',{name:'Admin'})).toHaveCount(0)
  await expect(page.getByText('Thoughtful member comment')).toBeVisible()
})
