import {test,expect,login} from './fixtures/bean'

test('draft is hidden then published to HTML, JSON, RSS, and CSV',async({page,bean})=>{
  await login(page,bean.baseURL)
  await expect(page.getByRole('heading',{name:'Administration'})).toBeVisible()
  await page.getByRole('link',{name:/Category/}).click()
  await page.getByRole('link',{name:'Add Category'}).click()
  await page.getByTestId('field-name').fill('Engineering')
  await page.getByTestId('create-category').click()
  await expect(page.getByRole('heading',{name:'Engineering'})).toBeVisible()
  await page.getByRole('link',{name:'Administration'}).click()
  await page.getByRole('link',{name:/Article/}).click()
  await page.getByRole('link',{name:'Add Article'}).click()
  await page.getByTestId('field-title').fill('Bean ships')
  await page.getByTestId('field-body').fill('Metadata works')
  await page.getByTestId('field-status').selectOption('draft')
  await page.getByTestId('field-category_id').selectOption({label:'Engineering'})
  await page.getByTestId('create-article').click()
  await expect(page.getByRole('heading',{name:'Bean ships'})).toBeVisible()
  expect(await (await page.request.get(bean.baseURL+'/api/news')).text()).not.toContain('Bean ships')
  await page.getByRole('combobox',{name:'Status'}).selectOption('published')
  await page.getByRole('button',{name:'Run for 1'}).click()
  await expect(page.getByRole('status')).toContainText('Action completed')
  await expect(page.locator('.history').getByText('Publish article')).toBeVisible()
  expect(await (await page.request.get(bean.baseURL+'/api/news')).text()).toContain('Bean ships')
  await page.getByRole('link',{name:'Article'}).click()
  await page.getByLabel('Search').fill('Bean')
  await page.getByRole('button',{name:'Apply'}).click()
  await expect(page.getByRole('link',{name:/Bean ships/})).toBeVisible()
  await page.getByRole('link',{name:/Bean ships/}).click()
  await page.getByTestId('field-body').fill('Metadata works better')
  await page.getByTestId('save-article').click()
  await expect(page).toHaveURL(/\/admin\/article$/)
  await page.getByRole('link',{name:/Bean ships/}).click()
  await expect(page.getByTestId('field-body')).toHaveValue('Metadata works better')
  await page.goto(bean.baseURL+'/')
  await expect(page.getByText('Bean ships')).toBeVisible()
  for(const path of ['/api/news','/news.rss','/news.csv'])expect(await (await page.request.get(bean.baseURL+path)).text()).toContain('Bean ships')
  await page.goto(bean.baseURL+'/admin/article')
  await page.getByRole('link',{name:/Bean ships/}).click()
  await page.getByRole('button',{name:'Delete'}).click()
  await page.getByRole('button',{name:'Confirm delete'}).click()
  await expect(page).toHaveURL(/\/admin\/article$/)
  await expect(page.getByText('Bean ships')).toHaveCount(0)
})
