import {expect,request as playwrightRequest} from '@playwright/test'
import {test as beanBase,login} from './fixtures/bean'
const test=beanBase.extend<{}, {appName:string}>({appName:['saas',{scope:'worker'}]})
async function user(baseURL:string,email:string){const api=await playwrightRequest.newContext({baseURL});const response=await api.post('/api/auth/login',{data:{email,password:'test-password'}});expect(response.ok()).toBeTruthy();return {api,csrf:(await response.json()).csrfToken}}

test('owner delivers a project and manages its lifecycle from the workspace',async({page,bean},testInfo)=>{
  await page.goto(bean.baseURL+'/')
  await expect(page.getByRole('heading',{name:'Team Workspace',exact:true})).toBeVisible()
  await expect(page.getByTestId('metric-value')).toHaveCount(0)
  await login(page,bean.baseURL,'owner-a@example.test','test-password',/\/$/)
  await expect(page.getByRole('heading',{name:'Northstar Studio'})).toBeVisible()
  await expect(page.getByTestId('metric-value')).toHaveText('6')
  await page.screenshot({path:testInfo.outputPath('overview-light.png'),fullPage:true})
  await page.getByRole('link',{name:'New',exact:true}).click()
  await page.getByRole('textbox',{name:/^name$/i}).fill('Partner onboarding')
  await page.getByRole('textbox',{name:/^description$/i}).fill('Prepare a useful first week for new partners.')
  await page.getByRole('button',{name:'Submit',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('Project created')
  await page.getByRole('link',{name:'Projects',exact:true}).click()
  const row=page.getByRole('row').filter({hasText:'Partner onboarding'})
  await expect(row.getByRole('cell',{name:'planned',exact:true})).toBeVisible()
  for(const [action,status]of [['start_project','active'],['complete_project','completed']]){
    await row.getByRole('checkbox').check()
    await page.getByRole('combobox',{name:'Action',exact:true}).selectOption(action)
    await page.getByRole('button',{name:'Run for 1',exact:true}).click()
    await expect(row.getByRole('cell',{name:status,exact:true})).toBeVisible()
  }
  await row.getByRole('link',{name:'Partner onboarding'}).click()
  await expect(page.getByRole('heading',{name:'Partner onboarding',exact:true})).toBeVisible()
  await page.getByRole('textbox',{name:/^name$/i}).fill('Partner launch')
  await page.getByRole('button',{name:'Submit',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('Project updated')
  await page.getByRole('link',{name:'Manage',exact:true}).click()
  const managed=page.getByRole('row').filter({hasText:'Partner launch'})
  for(const [action,status]of [['archive_project','archived'],['reopen_project','planned']]){
    await managed.getByRole('checkbox').check()
    await page.getByRole('combobox',{name:'Action',exact:true}).selectOption(action)
    await page.getByRole('button',{name:'Run for 1',exact:true}).click()
    await expect(managed.getByRole('cell',{name:status,exact:true})).toBeVisible()
  }
  await page.getByRole('link',{name:'Team Workspace',exact:true}).click()
  await expect(page.getByTestId('metric-value')).toHaveText('7')
  await page.getByRole('link',{name:'Settings',exact:true}).click()
  await page.getByRole('row').filter({hasText:'Northstar Studio'}).getByRole('checkbox').check()
  await page.getByRole('textbox',{name:/^name$/i}).fill('Northstar Delivery')
  await page.getByRole('button',{name:'Run for 1',exact:true}).click()
  await expect(page.getByRole('cell',{name:'Northstar Delivery',exact:true})).toBeVisible()
  await page.getByRole('link',{name:'Team Workspace',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Northstar Delivery'})).toBeVisible()
  await page.getByRole('button',{name:'Use dark theme'}).click()
  await page.screenshot({path:testInfo.outputPath('overview-dark.png'),fullPage:true})
})

test('member drills into scoped progress and another tenant has a different workspace',async({page,bean},testInfo)=>{
  await login(page,bean.baseURL,'member-a@example.test','test-password',/\/$/)
  await expect(page.getByTestId('metric-value')).toHaveText('6')
  await expect(page.getByRole('link',{name:'Manage',exact:true})).toHaveCount(0)
  await expect(page.getByRole('link',{name:'Settings',exact:true})).toHaveCount(0)
  await expect(page.getByRole('link',{name:'Admin',exact:true})).toHaveCount(0)
  await page.getByRole('combobox',{name:'Status',exact:true}).selectOption('active')
  await page.getByRole('button',{name:'Apply filters',exact:true}).click()
  await expect(page.getByTestId('metric-value')).toHaveText('2')
  await page.getByRole('link',{name:'Open active records',exact:true}).click()
  await expect(page).toHaveURL(/\/projects\?status=active/)
  await expect(page.getByRole('link',{name:'Autumn campaign',exact:true})).toBeVisible()
  await expect(page.getByRole('link',{name:'Client onboarding refresh',exact:true})).toHaveCount(0)
  await page.getByRole('link',{name:'Autumn campaign',exact:true}).click()
  const foreignURL=page.url()
  await login(page,bean.baseURL,'owner-b@example.test','test-password',/\/$/)
  await expect(page.getByRole('heading',{name:'Harbor Labs'})).toBeVisible()
  await expect(page.getByTestId('metric-value')).toHaveText('3')
  await expect(page.getByText('Autumn campaign',{exact:true})).toHaveCount(0)
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await page.screenshot({path:testInfo.outputPath('harbor-mobile.png'),fullPage:true})
  const foreignRead=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/views/project_record')
  await page.goto(foreignURL)
  expect(await (await foreignRead).text()).not.toContain('Autumn campaign')
  await expect(page.getByRole('heading',{name:'Autumn campaign',exact:true})).toHaveCount(0)
})

test('Views, aggregates, exports and Actions enforce tenant and role boundaries',async({bean})=>{
  const a=await user(bean.baseURL,'owner-a@example.test')
  const b=await user(bean.baseURL,'owner-b@example.test')
  const member=await user(bean.baseURL,'member-a@example.test')
  const anonymous=await playwrightRequest.newContext({baseURL:bean.baseURL})
  try{
    for(const path of ['/api/views/organisation_list','/api/projects','/api/views/project_total','/projects.csv'])expect((await anonymous.get(path)).status()).toBe(404)
    const projects=(await (await a.api.get('/api/projects')).json()).data
    const project=projects.find((row:any)=>row.status==='planned')
    const organisation=(await (await a.api.get('/api/views/organisation_list')).json()).data[0]
    expect(await (await b.api.get('/api/views/organisation_list')).text()).not.toContain('Northstar Studio')
    for(const [client,total]of [[a,6],[b,3]]as const){
      const result=await (await client.api.get('/api/views/project_total')).json()
      expect(result.data[0].project_count).toBe(total)
    }
    expect((await (await a.api.get('/api/views/project_total?status=active')).json()).data[0].project_count).toBe(2)
    expect((await (await b.api.get('/api/views/project_total?status=active')).json()).data[0].project_count).toBe(1)
    expect((await (await b.api.get('/api/projects?tenant_id=00000000-0000-4000-8000-00000000000a')).json()).data).toHaveLength(3)
    const exportA=await (await a.api.get('/projects.csv')).text()
    const exportB=await (await b.api.get('/projects.csv?tenant_id=00000000-0000-4000-8000-00000000000a')).text()
    expect(exportA).toContain(project.name)
    expect(exportB).not.toContain(project.name)
    expect(exportB).toContain('Research library')
    for(const action of ['project_update','project_delete','start_project','complete_project','archive_project','reopen_project']){
      expect((await b.api.post('/api/actions/'+action,{headers:{'X-CSRF-Token':b.csrf},data:{id:project.id,...(action==='project_update'?{name:'stolen'}:{})}})).status()).toBe(404)
    }
    for(const action of ['archive_project','reopen_project','project_delete'])expect((await member.api.post('/api/actions/'+action,{headers:{'X-CSRF-Token':member.csrf},data:{id:project.id}})).status()).toBe(409)
    expect((await member.api.post('/api/actions/organisation_update',{headers:{'X-CSRF-Token':member.csrf},data:{id:organisation.id,name:'changed'}})).status()).toBe(409)
    expect((await b.api.post('/api/actions/organisation_update',{headers:{'X-CSRF-Token':b.csrf},data:{id:organisation.id,name:'changed'}})).status()).toBe(404)
    expect((await a.api.post('/api/actions/project_update',{headers:{'X-CSRF-Token':a.csrf},data:{id:project.id,status:'completed'}})).ok()).toBe(false)
    expect((await a.api.post('/api/actions/complete_project',{headers:{'X-CSRF-Token':a.csrf},data:{id:project.id}})).status()).toBe(409)
    const made=await member.api.post('/api/actions/project_create',{headers:{'X-CSRF-Token':member.csrf},data:{name:'Member project'}})
    expect(made.ok()).toBeTruthy()
    expect((await made.json()).data.status).toBe('planned')
    expect((await member.api.post('/api/actions/start_project',{headers:{'X-CSRF-Token':member.csrf},data:{id:project.id}})).ok()).toBeTruthy()
    expect((await member.api.post('/api/actions/complete_project',{headers:{'X-CSRF-Token':member.csrf},data:{id:project.id}})).ok()).toBeTruthy()
    expect((await a.api.post('/api/actions/project_create',{headers:{'X-CSRF-Token':a.csrf},data:{name:'  '}})).status()).toBe(409)
  }finally{await Promise.all([a.api.dispose(),b.api.dispose(),member.api.dispose(),anonymous.dispose()])}
})
