import {FormEvent,useState} from 'react'
import {Link,Route,Routes,useNavigate,useParams} from 'react-router-dom'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {AdminManifest,AdminResource,api,Entity,Field} from './api'
import './system.css'

type Row=Record<string,any>
type AuditEntry={id:string;at:string;user_id:string;action:string;changed_fields:string;success:number;error:string}

export function Admin(){
  const manifest=useQuery({queryKey:['admin-manifest'],queryFn:()=>api<AdminManifest>('/api/admin/manifest')})
  if(manifest.isPending)return <main><p>Loading administration…</p></main>
  if(manifest.error)return <main className="narrow"><h1>Administration</h1><p role="alert">{manifest.error.message}</p><Link to="/login">Sign in</Link></main>
  return <main className="admin"><Routes><Route index element={<AdminHome manifest={manifest.data}/>}/><Route path="system" element={<SystemAdmin/>}/><Route path=":resource" element={<ResourceList manifest={manifest.data}/>}/><Route path=":resource/new" element={<ResourceRecord manifest={manifest.data} create/>}/><Route path=":resource/:id" element={<ResourceRecord manifest={manifest.data}/>}/></Routes></main>
}

function AdminHome({manifest}:{manifest:AdminManifest}){
  const resources=Object.entries(manifest.adminResources).sort((a,b)=>a[1].Label.localeCompare(b[1].Label))
  return <><div className="page-title"><div><h1>Administration</h1><p>Application data for release {manifest.version}.</p></div><span className="release-id">{manifest.releaseId}</span></div><div className="resource-grid"><Link className="resource-card system-card" to="/admin/system"><strong>System</strong><span>Users, releases, jobs, outbox, migrations, and audit.</span></Link>{resources.map(([name,resource])=><Link className="resource-card" key={name} to={'/admin/'+name}><strong>{resource.Label}</strong><span>{resource.Description||'Manage '+resource.Label.toLowerCase()}</span></Link>)}</div></>
}

type SystemUser={id:string;email:string;roles:string;tenant_id?:string;created_at:string}
type QueueRow={id:string;name?:string;topic?:string;status:string;attempts:number;max_attempts:number;next_attempt_at?:string;claimed_at?:string;last_error?:string}

function SystemAdmin(){
  const summary=useQuery({queryKey:['system-summary'],queryFn:()=>api<{releaseId:string;version:number;jobs:Record<string,number>;outbox:Record<string,number>}>('/api/admin/system/summary')})
  const users=useQuery({queryKey:['system-users'],queryFn:()=>api<SystemUser[]>('/api/admin/system/users')})
  const jobs=useQuery({queryKey:['system-jobs'],queryFn:()=>api<QueueRow[]>('/api/admin/system/jobs')})
  const outbox=useQuery({queryKey:['system-outbox'],queryFn:()=>api<QueueRow[]>('/api/admin/system/outbox')})
  const migrations=useQuery({queryKey:['system-migrations'],queryFn:()=>api<Row[]>('/api/admin/system/migrations')})
  const releases=useQuery({queryKey:['releases'],queryFn:()=>api<Row[]>('/api/admin/releases')})
  return <><nav className="breadcrumbs" aria-label="Breadcrumb"><Link to="/admin">Administration</Link><span>/</span><span>System</span></nav><div className="page-title"><div><h1>System</h1><p>Operational state and recovery controls.</p></div><span className="release-id">{summary.data?.releaseId||'No active release'}</span></div>{summary.error&&<p role="alert">{summary.error.message}</p>}<section><h2>Queue health</h2><div className="status-grid"><StatusGroup label="Jobs" counts={summary.data?.jobs}/><StatusGroup label="Outbox" counts={summary.data?.outbox}/></div></section><UserAdmin users={users.data||[]} loading={users.isPending} error={users.error}/><QueueAdmin label="Jobs" kind="jobs" rows={jobs.data||[]} loading={jobs.isPending} error={jobs.error}/><QueueAdmin label="Outbox" kind="outbox" rows={outbox.data||[]} loading={outbox.isPending} error={outbox.error}/><SystemTable title="Releases" rows={releases.data||[]} columns={['version','status','createdAt','activatedAt','id']}/><SystemTable title="Migrations" rows={migrations.data||[]} columns={['applied_at','release_id','sequence','description']}/></>
}

function StatusGroup({label,counts={}}:{label:string;counts?:Record<string,number>}){return <div><strong>{label}</strong>{Object.keys(counts).length===0?<span> No records</span>:<dl>{Object.entries(counts).sort().map(([status,count])=><div key={status}><dt>{humanize(status)}</dt><dd>{count}</dd></div>)}</dl>}</div>}

function UserAdmin({users,loading,error}:{users:SystemUser[];loading:boolean;error:Error|null}){
  const qc=useQueryClient();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[roles,setRoles]=useState('authenticated');const[tenantId,setTenantId]=useState('')
  const create=useMutation({mutationFn:()=>api('/api/admin/system/users',{method:'POST',body:JSON.stringify({email,password,roles:csv(roles),tenantId})}),onSuccess:()=>{setEmail('');setPassword('');void qc.invalidateQueries({queryKey:['system-users']})}})
  return <section><h2>Users and roles</h2><form className="list-tools" onSubmit={event=>{event.preventDefault();create.mutate()}}><label>Email<input type="email" required value={email} onChange={event=>setEmail(event.target.value)}/></label><label>Temporary password<input type="password" required minLength={10} value={password} onChange={event=>setPassword(event.target.value)}/></label><label>Roles<input value={roles} onChange={event=>setRoles(event.target.value)}/></label><label>Tenant ID<input value={tenantId} onChange={event=>setTenantId(event.target.value)}/></label><button type="submit" disabled={create.isPending}>Create user</button></form>{create.error&&<p role="alert">{create.error.message}</p>}{loading?<p>Loading users…</p>:error?<p role="alert">{error.message}</p>:<div className="table-wrap"><table><thead><tr><th>Email</th><th>Roles</th><th>Tenant</th><th>Created</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td>{user.email}</td><td><RoleEditor user={user}/></td><td>{display(user.tenant_id)}</td><td>{display(user.created_at)}</td></tr>)}</tbody></table></div>}</section>
}

function RoleEditor({user}:{user:SystemUser}){const qc=useQueryClient();const[value,setValue]=useState(jsonList(user.roles));const update=useMutation({mutationFn:()=>api('/api/admin/system/users/'+user.id+'/roles',{method:'PUT',body:JSON.stringify({roles:csv(value),tenantId:user.tenant_id||''})}),onSuccess:()=>void qc.invalidateQueries({queryKey:['system-users']})});return <form className="inline-form" onSubmit={event=>{event.preventDefault();update.mutate()}}><input aria-label={'Roles for '+user.email} value={value} onChange={event=>setValue(event.target.value)}/><button className="secondary" type="submit">Save</button>{update.error&&<span role="alert">{update.error.message}</span>}</form>}

function QueueAdmin({label,kind,rows,loading,error}:{label:string;kind:'jobs'|'outbox';rows:QueueRow[];loading:boolean;error:Error|null}){const qc=useQueryClient();const mutate=useMutation({mutationFn:({id,operation}:{id:string;operation:string})=>api('/api/admin/system/'+kind+'/'+id+'/'+operation,{method:'POST',body:'{}'}),onSuccess:()=>{void qc.invalidateQueries({queryKey:['system-'+kind]});void qc.invalidateQueries({queryKey:['system-summary']})}});return <section><h2>{label}</h2>{loading?<p>Loading {label.toLowerCase()}…</p>:error?<p role="alert">{error.message}</p>:rows.length===0?<p>No {label.toLowerCase()} records.</p>:<div className="table-wrap"><table><thead><tr><th>{kind==='jobs'?'Name':'Topic'}</th><th>Status</th><th>Attempts</th><th>Next retry</th><th>Last error</th><th>Controls</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.name||row.topic}</td><td>{row.status}</td><td>{row.attempts}/{row.max_attempts}</td><td>{display(row.next_attempt_at)}</td><td>{display(row.last_error)}</td><td>{row.status==='failed'&&<button onClick={()=>confirmQueue('retry',row,()=>mutate.mutate({id:row.id,operation:'retry'}))}>Retry</button>}{(row.status==='pending'||row.status==='failed')&&<button className="danger" onClick={()=>confirmQueue('cancel',row,()=>mutate.mutate({id:row.id,operation:'cancel'}))}>Cancel</button>}</td></tr>)}</tbody></table></div>}{mutate.error&&<p role="alert">{mutate.error.message}</p>}</section>}

function SystemTable({title,rows,columns}:{title:string;rows:Row[];columns:string[]}){return <section><h2>{title}</h2>{rows.length===0?<p>No {title.toLowerCase()} recorded.</p>:<div className="table-wrap"><table><thead><tr>{columns.map(column=><th key={column}>{humanize(column)}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={String(row.id||row.release_id||index)}>{columns.map(column=><td key={column}>{display(row[column])}</td>)}</tr>)}</tbody></table></div>}</section>}

function confirmQueue(operation:string,row:QueueRow,run:()=>void){if(window.confirm(`${humanize(operation)} ${row.name||row.topic||row.id}?`))run()}
function csv(value:string){return value.split(',').map(role=>role.trim()).filter(Boolean)}

function ResourceList({manifest}:{manifest:AdminManifest}){
  const {resource:name=''}=useParams();const resource=manifest.adminResources[name];
  const [query,setQuery]=useState('');const [submitted,setSubmitted]=useState('');const [filters,setFilters]=useState<Record<string,string>>({});const [sort,setSort]=useState('');const [direction,setDirection]=useState<'asc'|'desc'>('asc');const [cursors,setCursors]=useState<string[]>(['']);const [selected,setSelected]=useState<string[]>([])
  const cursor=cursors[cursors.length-1]
  const rows=useQuery({queryKey:['admin-resource',name,submitted,filters,sort,direction,cursor],enabled:Boolean(resource),queryFn:()=>api<{data:Row[];nextCursor:string}>('/api/admin/resources/'+name+'?'+params({q:submitted,cursor,sort,direction,...Object.fromEntries(Object.entries(filters).map(([key,value])=>['filter.'+key,value]))}))})
  if(!resource)return <NotFound/>
  const entity=manifest.entities[resource.Entity]
  function order(field:string){if(sort===field)setDirection(value=>value==='asc'?'desc':'asc');else{setSort(field);setDirection('asc')}setCursors([''])}
  const linkField=resource.List.Columns.includes(resource.LabelField)?resource.LabelField:resource.List.Columns[0]
  return <><Breadcrumb resource={resource}/><div className="page-title"><div><h1>{resource.Label}</h1>{resource.Description&&<p>{resource.Description}</p>}</div><Link className="button" to={'/admin/'+name+'/new'}>Add {resource.Label}</Link></div><section><form className="list-tools" onSubmit={(event)=>{event.preventDefault();setSubmitted(query);setCursors([''])}}><label>Search<input aria-label="Search" type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder={resource.List.Search.length?'Search '+resource.List.Search.join(', '):'Search unavailable'} disabled={!resource.List.Search.length}/></label>{resource.List.Filters.map(fieldName=><FilterControl key={fieldName} field={findField(entity,fieldName)} value={filters[fieldName]||''} onChange={value=>{setFilters(current=>({...current,[fieldName]:value}));setCursors([''])}}/>)}<button type="submit">Apply</button></form>{selected.length>0&&resource.Actions.length>0&&<ActionRunner manifest={manifest} resource={resource} ids={selected} onDone={()=>{setSelected([]);void rows.refetch()}}/>}{rows.isPending?<p>Loading records…</p>:rows.error?<p role="alert">{rows.error.message}</p>:rows.data.data.length===0?<div className="empty"><p>No records match this view.</p><Link to={'/admin/'+name+'/new'}>Create the first one</Link></div>:<div className="table-wrap"><table><thead><tr><th><input aria-label="Select all" type="checkbox" checked={rows.data.data.length>0&&selected.length===rows.data.data.length} onChange={event=>setSelected(event.target.checked?rows.data.data.map(row=>String(row.id)):[])}/></th>{resource.List.Columns.map(field=><th key={field}><button className="sort" onClick={()=>order(field)}>{fieldLabel(entity,field)} {sort===field?(direction==='asc'?'↑':'↓'):''}</button></th>)}</tr></thead><tbody>{rows.data.data.map(row=><tr key={row.id}><td><input aria-label={'Select '+String(row[resource.LabelField]||row.id)} type="checkbox" checked={selected.includes(String(row.id))} onChange={event=>setSelected(current=>event.target.checked?[...current,String(row.id)]:current.filter(id=>id!==String(row.id)))}/></td>{resource.List.Columns.map(field=><td key={field}>{field===linkField?<Link to={'/admin/'+name+'/'+row.id}>{display(row[field])}</Link>:display(row[field])}</td>)}</tr>)}</tbody></table></div>}<nav className="pager" aria-label="Pagination"><button disabled={cursors.length===1} onClick={()=>setCursors(current=>current.slice(0,-1))}>Previous</button><button disabled={!rows.data?.nextCursor} onClick={()=>setCursors(current=>[...current,rows.data?.nextCursor||''])}>Next</button></nav></section></>
}

function ResourceRecord({manifest,create=false}:{manifest:AdminManifest;create?:boolean}){
  const {resource:name='',id=''}=useParams();const resource=manifest.adminResources[name]
  const record=useQuery({queryKey:['admin-record',name,id],enabled:Boolean(resource&&!create),queryFn:()=>api<{data:Row}>('/api/admin/resources/'+name+'/'+id)})
  if(!resource)return <NotFound/>
  if(!create&&record.isPending)return <p>Loading record…</p>
  if(!create&&record.error)return <p role="alert">{record.error.message}</p>
  return <RecordEditor key={create?'new':id} manifest={manifest} resource={resource} initial={create?{}:record.data?.data||{}} create={create}/>
}

function RecordEditor({manifest,resource,initial,create}:{manifest:AdminManifest;resource:AdminResource;initial:Row;create:boolean}){
  const entity=manifest.entities[resource.Entity];const nav=useNavigate();const qc=useQueryClient();const [values,setValues]=useState<Row>(initial);const [confirmDelete,setConfirmDelete]=useState(false)
  const save=useMutation({mutationFn:()=>{const action=create?resource.CreateAction:resource.UpdateAction;const body=create?pick(values,resource.Form.Fields):{id:initial.id,...changed(initial,values,resource.Form.Fields)};return api<{data:Row}>('/api/actions/'+action,{method:'POST',body:JSON.stringify(body)})},onSuccess:result=>{qc.setQueryData(['admin-record',resource.Name,result.data.id],result);void qc.invalidateQueries({queryKey:['admin-resource',resource.Name]});nav(create?'/admin/'+resource.Name+'/'+result.data.id:'/admin/'+resource.Name)}})
  const remove=useMutation({mutationFn:()=>api('/api/actions/'+resource.DeleteAction,{method:'POST',body:JSON.stringify({id:initial.id})}),onSuccess:()=>{void qc.invalidateQueries({queryKey:['admin-resource',resource.Name]});nav('/admin/'+resource.Name)}})
  const protectedFields=new Set(Object.values(manifest.actions).filter(action=>action.Entity===resource.Entity&&action.Operation==='transition').map(action=>action.StateField||'status'))
  return <><Breadcrumb resource={resource} current={create?'Add':String(initial[resource.LabelField]||initial.id)}/><div className="page-title"><h1>{create?'Add '+resource.Label:String(initial[resource.LabelField]||resource.Label)}</h1>{!create&&<button className="danger secondary" onClick={()=>setConfirmDelete(true)}>Delete</button>}</div><section><form onSubmit={(event)=>{event.preventDefault();save.mutate()}}>{resource.Form.Fields.map(name=>{const field=findField(entity,name);const readonly=!create&&protectedFields.has(name);return field?<AdminField key={name} field={field} value={readonly?initial[name]:values[name]} readonly={readonly} manifest={manifest} onChange={value=>setValues(current=>({...current,[name]:value}))}/>:null})}{save.error&&<p role="alert">{save.error.message}</p>}<button data-testid={create?'create-'+resource.Entity:'save-'+resource.Entity} type="submit" disabled={save.isPending}>{save.isPending?'Saving…':'Save'}</button><Link className="button secondary" to={'/admin/'+resource.Name}>Cancel</Link></form>{!create&&<dl className="metadata">{resource.Form.Readonly.map(name=><div key={name}><dt>{fieldLabel(entity,name)}</dt><dd>{display(initial[name])}</dd></div>)}</dl>}</section>{!create&&resource.Actions.length>0&&<section><h2>Actions</h2><ActionRunner manifest={manifest} resource={resource} ids={[String(initial.id)]} onDone={()=>{void qc.invalidateQueries({queryKey:['admin-record',resource.Name,initial.id]});void qc.invalidateQueries({queryKey:['admin-history',resource.Entity,initial.id]})}}/></section>}{!create&&<History entity={resource.Entity} id={String(initial.id)}/>} {confirmDelete&&<div className="confirm" role="alertdialog" aria-labelledby="delete-title"><div><h2 id="delete-title">Delete this {resource.Label.toLowerCase()}?</h2><p>This operation cannot be undone.</p>{remove.error&&<p role="alert">{remove.error.message}</p>}<button className="danger" onClick={()=>remove.mutate()}>Confirm delete</button><button className="secondary" onClick={()=>setConfirmDelete(false)}>Cancel</button></div></div>}</>
}

function AdminField({field,value,onChange,manifest,readonly=false,idPrefix='admin'}:{field:Field;value:any;onChange:(value:any)=>void;manifest:AdminManifest;readonly?:boolean;idPrefix?:string}){
  const id=idPrefix+'-'+field.Name;if(readonly)return <label htmlFor={id}>{field.Label||field.Name}<input id={id} value={display(value)} readOnly/></label>
  if(field.Type==='relation')return <RelationControl field={field} value={value} onChange={onChange} manifest={manifest}/>
  if(field.Type==='enum')return <label htmlFor={id}>{field.Label||field.Name}<select id={id} data-testid={'field-'+field.Name} required={field.Required} value={value??''} onChange={event=>onChange(event.target.value)}><option value="">Select…</option>{field.Options?.map(option=><option key={option}>{option}</option>)}</select></label>
  if(field.Type==='boolean')return <label className="checkbox" htmlFor={id}><input id={id} data-testid={'field-'+field.Name} type="checkbox" checked={Boolean(value)} onChange={event=>onChange(event.target.checked)}/>{field.Label||field.Name}</label>
  if(field.Type==='text'||field.Type==='richtext')return <label htmlFor={id}>{field.Label||field.Name}<textarea id={id} data-testid={'field-'+field.Name} required={field.Required} value={value??''} onChange={event=>onChange(event.target.value)}/></label>
  const numeric=['integer','money','decimal'].includes(field.Type);const type=numeric?'number':field.Type==='email'?'email':field.Type==='date'?'date':field.Type==='datetime'?'datetime-local':'text'
  return <label htmlFor={id}>{field.Label||field.Name}<input id={id} data-testid={'field-'+field.Name} type={type} required={field.Required} value={value??''} onChange={event=>onChange(numeric?(event.target.value===''?'':Number(event.target.value)):event.target.value)}/></label>
}

function RelationControl({field,value,onChange,manifest}:{field:Field;value:any;onChange:(value:any)=>void;manifest:AdminManifest}){
  const target=Object.values(manifest.adminResources).find(resource=>resource.Entity===field.Relation?.Entity);const options=useQuery({queryKey:['admin-relation',target?.Name],enabled:Boolean(target),queryFn:()=>api<{data:Row[]}>('/api/admin/resources/'+target?.Name+'?limit=200')});const multiple=field.Relation?.Kind==='one-to-many'||field.Relation?.Kind==='many-to-many';const selected=multiple?(Array.isArray(value)?value:[]):value??''
  return <label>{field.Label||field.Name}<select data-testid={'field-'+field.Name} multiple={multiple} required={field.Required} value={selected} onChange={event=>onChange(multiple?Array.from(event.target.selectedOptions,option=>option.value):event.target.value)}><option value="">Select…</option>{options.data?.data.map(row=><option key={row.id} value={row.id}>{display(row[target?.LabelField||'id'])}</option>)}</select>{!target&&<span className="hint">No admin resource exists for the related entity.</span>}</label>
}

function FilterControl({field,value,onChange}:{field?:Field;value:string;onChange:(value:string)=>void}){if(!field)return null;const id='filter-'+field.Name;return <label htmlFor={id}>{field.Label||field.Name}{field.Type==='enum'?<select id={id} value={value} onChange={event=>onChange(event.target.value)}><option value="">All</option>{field.Options?.map(option=><option key={option}>{option}</option>)}</select>:field.Type==='boolean'?<select id={id} value={value} onChange={event=>onChange(event.target.value)}><option value="">All</option><option value="true">Yes</option><option value="false">No</option></select>:<input id={id} value={value} onChange={event=>onChange(event.target.value)}/>}</label>}

function ActionRunner({manifest,resource,ids,onDone}:{manifest:AdminManifest;resource:AdminResource;ids:string[];onDone:()=>void}){
  const [name,setName]=useState(resource.Actions[0]||'');const [values,setValues]=useState<Row>({});const [result,setResult]=useState('');const action=manifest.actions[name]
  const run=useMutation({mutationFn:async()=>{const failures:string[]=[];for(const id of ids){try{await api('/api/actions/'+name,{method:'POST',body:JSON.stringify({...values,id})})}catch(error){failures.push(id+': '+(error as Error).message)}}if(failures.length)throw new Error(failures.join('; '))},onSuccess:()=>{setResult('Action completed for '+ids.length+' record'+(ids.length===1?'':'s')+'.');onDone()}})
  if(!resource.Actions.length)return null
  return <form className="action-runner" onSubmit={(event:FormEvent)=>{event.preventDefault();run.mutate()}}><label>Action<select aria-label="Action" value={name} onChange={event=>{setName(event.target.value);setValues({});setResult('')}}>{resource.Actions.map(actionName=><option key={actionName} value={actionName}>{humanize(actionName)}</option>)}</select></label>{action&&Object.entries(action.Input).filter(([input])=>input!=='id').map(([input,field])=><AdminField key={input} field={field} value={values[input]} manifest={manifest} idPrefix={'action-'+name} onChange={value=>setValues(current=>({...current,[input]:value}))}/>)}<button type="submit" disabled={run.isPending}>{run.isPending?'Running…':'Run for '+ids.length}</button>{run.error&&<p role="alert">{run.error.message}</p>}{result&&<p role="status">{result}</p>}</form>
}

function History({entity,id}:{entity:string;id:string}){const history=useQuery({queryKey:['admin-history',entity,id],queryFn:()=>api<AuditEntry[]>('/api/admin/audit?'+params({entity,id}))});return <section><h2>History</h2>{history.isPending?<p>Loading history…</p>:history.error?<p role="alert">{history.error.message}</p>:history.data.length===0?<p>No changes recorded.</p>:<ol className="history">{history.data.map(entry=><li key={entry.id}><strong>{humanize(entry.action)}</strong><span>{new Date(entry.at).toLocaleString()} · {entry.success?'Succeeded':'Failed'}</span>{entry.changed_fields&&<small>Fields: {jsonList(entry.changed_fields)}</small>}{entry.error&&<small>{entry.error}</small>}</li>)}</ol>}</section>}

function Breadcrumb({resource,current}:{resource:AdminResource;current?:string}){return <nav className="breadcrumbs" aria-label="Breadcrumb"><Link to="/admin">Administration</Link><span>/</span>{current?<><Link to={'/admin/'+resource.Name}>{resource.Label}</Link><span>/</span><span>{current}</span></>:<span>{resource.Label}</span>}</nav>}
function NotFound(){return <><h1>Admin resource not found</h1><Link to="/admin">Back to administration</Link></>}
function findField(entity:Entity,name:string){return entity.Fields.find(field=>field.Name===name)}
function fieldLabel(entity:Entity,name:string){if(name==='id')return 'ID';return findField(entity,name)?.Label||humanize(name)}
function humanize(value:string){return value.replaceAll('_',' ').replace(/^./,letter=>letter.toUpperCase())}
function display(value:any){if(value===null||value===undefined||value==='')return '—';if(typeof value==='boolean')return value?'Yes':'No';if(Array.isArray(value))return value.join(', ');return String(value)}
function params(values:Record<string,string>){const query=new URLSearchParams();for(const [key,value] of Object.entries(values))if(value)query.set(key,value);return query.toString()}
function pick(values:Row,fields:string[]){return Object.fromEntries(fields.filter(field=>values[field]!==undefined&&values[field]!=='').map(field=>[field,values[field]]))}
function changed(before:Row,after:Row,fields:string[]){return Object.fromEntries(fields.filter(field=>after[field]!==before[field]).map(field=>[field,after[field]]))}
function jsonList(value:string){try{return (JSON.parse(value) as string[]).join(', ')}catch{return value}}
