import {createContext,FormEvent,useContext,useEffect,useMemo,useRef,useState} from 'react'
import {Link,Route,Routes,useLocation,useNavigate,useSearchParams} from 'react-router-dom'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {api,APIError,FormElement,Manifest,Node,PageFilter,Session,ViewDisplay,ViewDrill,ViewFilter,ViewPresentation} from './api'
import {callAction,encodeInput,runActionBatch} from './action-client'
import {Admin,ResourceListBlock} from './Admin'
import {Studio} from './Studio'
import {Explore} from './Explore'
import {ContentBlock,SequenceView} from './Sequence'
import {ErrorAlert,Field,LoadingState,Page,PageHeader,SectionCard,StatusAlert} from '@/components/bean'
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle} from '@/components/ui/alert-dialog'
import {Button} from '@/components/ui/button'
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from '@/components/ui/card'
import {Checkbox} from '@/components/ui/checkbox'
import {Input} from '@/components/ui/input'
import {Label} from '@/components/ui/label'
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select'
import {Textarea} from '@/components/ui/textarea'
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table'

type Row=Record<string,any>
const noPageFilters:Record<string,string>={}
const CurrentPath=createContext<React.MutableRefObject<string>|null>(null)
const PageFilterValues=createContext<Record<string,string>>(noPageFilters)

function Login(){
  const nav=useNavigate();const loc=useLocation();const qc=useQueryClient()
  const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('')
  async function submit(event:FormEvent){
    event.preventDefault()
    try{
      const result=await api<{csrfToken:string;user:{Roles:string[]}}>('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})})
      sessionStorage.setItem('bean_csrf',result.csrfToken)
      await qc.cancelQueries()
      qc.clear()
      const fallback=result.user.Roles.some(role=>role==='editor'||role==='administrator')?'/admin':'/'
      const requested=new URLSearchParams(loc.search).get('next')||fallback
      nav(requested.startsWith('/')&&!requested.startsWith('//')?requested:fallback)
    }catch(cause){setError((cause as Error).message)}
  }
  return <Shell><Page narrow><Card><CardHeader><CardTitle><h1 className="text-2xl">Sign in</h1></CardTitle><CardDescription>Access your Bean application.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={submit}><Field id="login-email" label="Email"><Input id="login-email" data-testid="email" type="email" required value={email} onChange={event=>setEmail(event.target.value)}/></Field><Field id="login-password" label="Password"><Input id="login-password" data-testid="password" type="password" required value={password} onChange={event=>setPassword(event.target.value)}/></Field>{error&&<ErrorAlert error={error}/>}<Button className="w-full" data-testid="login" type="submit">Sign in</Button></form></CardContent></Card></Page></Shell>
}

function Shell({children,chrome=true}:{children:React.ReactNode;chrome?:boolean}){
  const loc=useLocation();const nav=useNavigate();const qc=useQueryClient();const currentPath=useContext(CurrentPath);const logoutStarted=useRef(false)
  const session=useQuery({queryKey:['session'],queryFn:()=>api<Session>('/api/system/session')})
  const manifest=useQuery({queryKey:['manifest'],queryFn:()=>api<Manifest>('/api/system/manifest')})
  useEffect(()=>{if(session.data?.authenticated&&session.data.csrfToken)sessionStorage.setItem('bean_csrf',session.data.csrfToken)},[session.data?.authenticated,session.data?.csrfToken])
  const roles=session.data?.user?.Roles||[]
  const editor=roles.includes('editor')||roles.includes('administrator')
  const administrator=roles.includes('administrator')
	const theme=manifest.data?.theme
  const logout=useMutation({mutationFn:async()=>{const path=loc.pathname;const result=await api<{protected?:boolean}>('/api/auth/logout?path='+encodeURIComponent(path),{method:'POST',body:'{}'});return {path,protected:path.startsWith('/admin')||path.startsWith('/studio')||path.startsWith('/explore')||result.protected===true}},onSuccess:async result=>{sessionStorage.removeItem('bean_csrf');await qc.resetQueries();const routeChanged=currentPath?.current!==result.path;logoutStarted.current=false;if(result.protected||routeChanged)nav('/',{replace:true})},onError:()=>{logoutStarted.current=false}})
  const stopNavigation=(event:React.MouseEvent)=>{if(logoutStarted.current||logout.isPending)event.preventDefault()}
  return <div className="min-h-screen bg-background" data-testid="application-shell" data-preset={theme?.Preset||'professional'} data-accent={theme?.Accent||'emerald'}>{chrome&&<header className="border-b bg-primary text-primary-foreground"><div className="mx-auto flex w-full max-w-6xl flex-col gap-3 px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><Link className="text-lg font-semibold tracking-tight" to="/" aria-disabled={logout.isPending} onClick={stopNavigation}>{theme?.DisplayName||'Bean'}</Link><nav className="flex flex-wrap items-center gap-1" aria-label="Primary navigation">{editor&&<Button variant="ghost" disabled={logout.isPending} asChild><Link to="/admin" aria-disabled={logout.isPending} onClick={stopNavigation}>Admin</Link></Button>}{administrator&&<Button variant="ghost" disabled={logout.isPending} asChild><Link to="/explore" aria-disabled={logout.isPending} onClick={stopNavigation}>Explore</Link></Button>}{administrator&&<Button variant="ghost" disabled={logout.isPending} asChild><Link to="/studio" aria-disabled={logout.isPending} onClick={stopNavigation}>Studio</Link></Button>}{session.data?.authenticated?<Button variant="ghost" onClick={()=>{logoutStarted.current=true;logout.mutate()}} disabled={logout.isPending}>Sign out</Button>:manifest.data?.authNavigation!==false?<>{manifest.data?.localRegistration?.Route&&<Button variant="ghost" asChild><Link to={manifest.data.localRegistration.Route}>Sign up</Link></Button>}<Button variant="secondary" asChild><Link to={'/login?next='+encodeURIComponent(loc.pathname)}>Sign in</Link></Button></>:null}</nav></div></header>}{children}</div>
}

type RenderProps={
  Page:{title?:string;description?:string;protected?:boolean;filters?:Record<string,PageFilter>}
  Panel:{layout?:string}
  Region:{name?:string}
  TextBlock:{text?:string}
  ContentBlock:{content?:import('./api').ContentElement[]}
  Sequence:{title?:string;description?:string;profile?:string;aspectRatio?:string;protected?:boolean}
  ViewBlock:{name?:string;view?:string;display?:ViewDisplay;displayName?:string;displays?:Record<string,ViewDisplay>;filters?:Record<string,ViewFilter>;pageFilters?:Record<string,string>;fieldTypes?:Record<string,string>;presentation?:ViewPresentation;searchFields?:string[];formattedFields?:string[];fileFields?:string[];maxRows?:number}
  EntityBlock:{name?:string;entity?:string;presentation?:ViewPresentation;formattedFields?:string[];fileFields?:string[]}
  ResourceListBlock:{name?:string;resource?:string;view?:string;filters?:string[];defaultFilters?:Record<string,any>}
  WebformBlock:{name?:string;webform?:string;form?:Manifest['webforms'][string]}
  ActionBlock:{action?:string}
  MenuBlock:{items?:Array<{Route:string;Label:string}>}
}
type RenderComponent=keyof RenderProps
type NodeRenderer<K extends RenderComponent>=(props:RenderProps[K],children?:Node[])=>React.ReactNode
const nodeRenderers:{[K in RenderComponent]:NodeRenderer<K>}={
  Page:(props,children)=><PageNode title={props.title} description={props.description} filters={props.filters||{}} children={children}/>,
  Panel:(props,children)=><StructuralNode component="Panel" layout={props.layout} children={children}/>,
  Region:(props,children)=><StructuralNode component="Region" name={props.name} children={children}/>,
  TextBlock:props=><p>{props.text}</p>,
  ContentBlock:props=><ContentBlock content={props.content||[]}/>,
  Sequence:(props,children)=><SequenceView {...props} children={children} renderNode={node=><Renderer node={node}/>}/>,
  ViewBlock:props=><ViewBlock name={props.view||''} block={props.name||''} display={props.display} displayName={props.displayName} displays={props.displays} filters={props.filters||{}} pageFilters={props.pageFilters||noPageFilters} fieldTypes={props.fieldTypes||{}} presentation={props.presentation||{}} searchFields={props.searchFields||[]} formattedFields={props.formattedFields||[]} fileFields={props.fileFields||[]} maxRows={props.maxRows}/>,
  EntityBlock:props=><ViewBlock name={(props.entity||'')+'_list'} block={props.name||''} presentation={props.presentation||{}} formattedFields={props.formattedFields||[]} fileFields={props.fileFields||[]}/>,
  ResourceListBlock:props=><ResourceListBlock resource={props.resource||''} view={props.view||''} block={props.name||''} filters={props.filters} defaultFilters={props.defaultFilters}/>,
  WebformBlock:props=><WebformBlock name={props.webform||''} block={props.name||''} renderedForm={props.form}/>,
  ActionBlock:props=><ActionBlock name={props.action||''}/>,
  MenuBlock:props=><MenuBlock items={props.items||[]}/>,
}
function isRenderComponent(value:string):value is RenderComponent{return Object.hasOwn(nodeRenderers,value)}
function renderKnownNode(component:RenderComponent,props:Record<string,any>,children?:Node[]){const renderer=nodeRenderers[component] as NodeRenderer<RenderComponent>;return renderer(props,children)}
function StructuralNode({component,title,layout,name,children}:{component:'Page'|'Panel'|'Region';title?:string;layout?:string;name?:string;children?:Node[]}){useEffect(()=>{if(component!=='Page'||!title)return;const previous=document.title;document.title=title;return()=>{document.title=previous}},[component,title]);const className=component==='Panel'?'bean-panel':component==='Region'?'bean-region':'space-y-4';return <section className={className} data-component={component} data-layout={layout} data-region={name}>{title&&<h2 className="font-heading text-2xl font-semibold">{title}</h2>}{children?.map((child,index)=><Renderer key={index} node={child}/>)}</section>}
function PageNode({title,description,filters,children}:{title?:string;description?:string;filters:Record<string,PageFilter>;children?:Node[]}){const[urlParams,setURLParams]=useSearchParams();const names=Object.keys(filters);const[state,setState]=useState<Record<string,string>>(()=>Object.fromEntries(names.map(name=>{const value=urlParams.get(name)??String(filters[name].Default??'');return[name,controlInputValue(value,{Type:filters[name].Type})]})));useEffect(()=>{if(!title)return;const previous=document.title;document.title=title;return()=>{document.title=previous}},[title]);const urlState=urlParams.toString();const filterState=JSON.stringify(filters);useEffect(()=>{const definitions=JSON.parse(filterState)as Record<string,PageFilter>;const current=new URLSearchParams(urlState);setState(Object.fromEntries(Object.keys(definitions).map(name=>{const value=current.get(name)??String(definitions[name].Default??'');return[name,controlInputValue(value,{Type:definitions[name].Type})]})))},[filterState,urlState]);const values=Object.fromEntries(names.map(name=>[name,urlParams.get(name)??String(filters[name].Default??'')]));const apply=(event:FormEvent)=>{event.preventDefault();const next=new URLSearchParams(urlParams);for(const name of names){const definition={Type:filters[name].Type};const original=urlParams.get(name)??String(filters[name].Default??'');const value=controlQueryValue(state[name]??'',definition,original);if(value||filters[name].Default!==undefined&&filters[name].Default!==null)next.set(name,value);else next.delete(name)}setURLParams(next,{replace:true})};return <PageFilterValues.Provider value={values}><section className="space-y-4" data-component="Page">{title&&<h2 className="font-heading text-2xl font-semibold">{title}</h2>}{description&&<p className="text-muted-foreground">{description}</p>}{names.length?<form className="grid items-end gap-4 sm:grid-cols-2 lg:flex lg:flex-wrap" aria-label="Page filters" onSubmit={apply}>{names.map(name=><ViewFilterControl key={name} scope="page" control={{Filter:name,Label:filters[name].Label,Widget:filters[name].Widget}} filter={{Type:filters[name].Type,Options:filters[name].Options}} value={state[name]??''} onChange={value=>setState(current=>({...current,[name]:value}))}/>)}<Button type="submit">Apply filters</Button></form>:null}{children?.map((child,index)=><Renderer key={index} node={child}/>)}</section></PageFilterValues.Provider>}
function Renderer({node}:{node:Node}){
  if(!isRenderComponent(node.component))return <section role="alert" data-component={node.component}>Unsupported render component: {node.component}</section>
  return renderKnownNode(node.component,node.props||{},node.children)
}

type ViewBlockProps={name:string;block:string;display?:ViewDisplay;displayName?:string;displays?:Record<string,ViewDisplay>;filters?:Record<string,ViewFilter>;pageFilters?:Record<string,string>;fieldTypes?:Record<string,string>;presentation:ViewPresentation;searchFields?:string[];formattedFields:string[];fileFields:string[];maxRows?:number}
function ViewBlock(props:ViewBlockProps){
  const path=useLocation().pathname
  return <ViewBlockPage key={`${props.name}:${props.block}:${path}`} {...props} path={path}/>
}
function ViewBlockPage({name,block,display,displayName,displays={},filters={},pageFilters=noPageFilters,fieldTypes={},presentation,searchFields=[],formattedFields,fileFields,maxRows,path}:ViewBlockProps&{path:string}){
	const[cursors,setCursors]=useState<string[]>([''])
	const[search,setSearch]=useState('');const[submittedSearch,setSubmittedSearch]=useState('')
	const[urlParams,setURLParams]=useSearchParams();const pageFilterValues=useContext(PageFilterValues);const boundPageFilters=Object.fromEntries(Object.entries(pageFilters).map(([filter,pageFilter])=>[filter,pageFilterValues[pageFilter]??urlParams.get(pageFilter)??'']));const pageFilterSignature=JSON.stringify(Object.entries(boundPageFilters).sort());const cursorPageFilterSignature=useRef(pageFilterSignature);const cursor=cursorPageFilterSignature.current===pageFilterSignature?cursors[cursors.length-1]:'';useEffect(()=>{if(cursorPageFilterSignature.current===pageFilterSignature)return;cursorPageFilterSignature.current=pageFilterSignature;setCursors([''])},[pageFilterSignature])
	const displayParameter=block+'.display';const activeDisplayName=urlParams.get(displayParameter)||displayName||'';display=displays[activeDisplayName]||display;const controls=useMemo(()=>(display?.Controls||[]).filter(control=>!pageFilters[control.Filter]),[display?.Controls,pageFilters]);const pageDisplay=display?.Type==='page'
	const parameter=(filter:string)=>pageDisplay?filter:block+'.'+filter
	const initialControls=()=>Object.fromEntries(controls.map(control=>{const value=urlParams.get(parameter(control.Filter))??String(control.Default??'');return[control.Filter,controlInputValue(value,filters[control.Filter])]}))
	const[controlValues,setControlValues]=useState<Record<string,string>>(initialControls)
	const urlState=urlParams.toString()
	useEffect(()=>setControlValues(Object.fromEntries(controls.map(control=>{const value=urlParams.get(pageDisplay?control.Filter:block+'.'+control.Filter)??String(control.Default??'');return[control.Filter,controlInputValue(value,filters[control.Filter])]}))),[block,controls,filters,pageDisplay,urlParams,urlState])
	const mode=display?.Renderer?.Type||presentation.Mode
	const rowLimit=maxRows&&maxRows>0?maxRows:200
	const renderer=display?.Renderer
	const effectivePresentation:ViewPresentation=renderer?{Mode:renderer.Type,TitleField:renderer.TitleField,BodyField:renderer.BodyField,LinkRoute:renderer.LinkRoute,LinkField:renderer.LinkField,EmptyState:renderer.EmptyState||display.EmptyState,MetaFields:renderer.MetaFields,RichTextFields:renderer.RichTextFields,GroupField:renderer.GroupField,OrderField:renderer.OrderField,ParentField:renderer.ParentField,MoveAction:renderer.MoveAction,Columns:renderer.Columns,MetricField:renderer.MetricField,MetricLabel:renderer.MetricLabel,TimeField:renderer.TimeField,EndField:renderer.EndField,SearchFields:renderer.SearchFields}:presentation
	const query=new URLSearchParams({_page:path});if(pageDisplay)query.set('_display',block);else{query.set('_block',block);if(activeDisplayName)query.set('_viewDisplay',activeDisplayName)}for(const[filter,value]of Object.entries(boundPageFilters))if(value)query.set(filter,value);for(const control of controls)query.set(control.Filter,urlParams.get(parameter(control.Filter))??String(control.Default??''));if(mode==='board'||mode==='tree'||mode==='calendar'||mode==='chart')query.set('limit','200');else if(mode==='detail')query.set('limit',String(rowLimit));else if(display?.Pager?.PageSize)query.set('limit',String(display.Pager.PageSize));if(cursor)query.set('cursor',cursor);if(submittedSearch)query.set('q',submittedSearch)
  const request='/api/views/'+name+'?'+query.toString()
	const structured=mode==='board'||mode==='tree'||mode==='detail';const structuredLimit=mode==='detail'?rowLimit:200;const structuredLimitError=`This View display supports at most ${structuredLimit} rows.`
  const result=useQuery({queryKey:['public-view',request],queryFn:async()=>{const first=await api<{data:Row[];nextCursor:string}>(request);if(!structured)return first;const data=[...first.data];if(data.length>structuredLimit||(mode==='detail'&&first.nextCursor))throw new APIError(structuredLimitError);if(mode==='detail')return {data,nextCursor:''};let nextCursor=first.nextCursor;while(nextCursor&&data.length<200){const nextQuery=new URLSearchParams(query);nextQuery.set('cursor',nextCursor);nextQuery.set('limit',String(200-data.length));const next=await api<{data:Row[];nextCursor:string}>('/api/views/'+name+'?'+nextQuery);data.push(...next.data);if(data.length>200)throw new APIError(structuredLimitError);nextCursor=next.nextCursor}if(nextCursor)throw new APIError(structuredLimitError);return {data,nextCursor:''}}})
	const resultTitle=display?.Title?.Field?result.data?.data[0]?.[display.Title.Field]:undefined
	const resolvedTitle=display?.Title?.Field?(resultTitle===null||resultTitle===undefined||resultTitle===''?display.Title.Fallback||'':String(resultTitle)):display?.Title?.Text||''
	useEffect(()=>{if(!pageDisplay||!resolvedTitle)return;const previous=document.title;document.title=resolvedTitle;return()=>{document.title=previous}},[pageDisplay,resolvedTitle])
	let content:React.ReactNode
	if(result.isPending)content=<LoadingState/>
	else if(result.error)content=<ErrorAlert error={result.error}/>
	else if(!result.data.data.length)content=<Card><CardContent className="py-8 text-center text-muted-foreground">{display?.EmptyState||effectivePresentation.EmptyState||'Nothing to show.'}</CardContent></Card>
	else if(mode==='table')content=<TableView key={[activeDisplayName,display?.Selection,...(display?.Actions||[])].join('|')} rows={result.data.data} fields={renderer?.Fields||[]} fieldTypes={fieldTypes} display={display}/>
	else if(mode==='board')content=<BoardView rows={result.data.data} presentation={effectivePresentation}/>
	else if(mode==='tree')content=<TreeView rows={result.data.data} presentation={effectivePresentation}/>
	else if(mode==='metric')content=<MetricView row={result.data.data[0]} presentation={effectivePresentation} drill={display?.Drill} filters={Object.fromEntries(query)}/>
	else if(mode==='chart')content=<ChartView rows={result.data.data} presentation={effectivePresentation} drill={display?.Drill} filters={Object.fromEntries(query)}/>
	else if(mode==='calendar')content=<CalendarView rows={result.data.data} presentation={effectivePresentation}/>
	else if(mode==='timeline')content=<div className="space-y-4"><TimelineView rows={result.data.data} presentation={effectivePresentation}/>{display?.Pager?.Type!=='none'&&<Pagination previousDisabled={cursors.length===1} nextDisabled={!result.data.nextCursor} previous={()=>setCursors(value=>value.slice(0,-1))} next={()=>setCursors(value=>[...value,result.data.nextCursor])}/>}</div>
	else{const rows=mode==='detail'?[mergeDetail(result.data.data,effectivePresentation.MetaFields||[])]:result.data.data;content=<div className="space-y-4">{rows.map(row=><Card key={String(row.id)+JSON.stringify(row)}><CardHeader>{!(mode==='detail'&&display?.Title?.Field)&&<CardTitle><h3>{effectivePresentation.LinkRoute?<Link className="hover:underline" to={viewLink(effectivePresentation.LinkRoute,row)}>{row[effectivePresentation.TitleField||'title']}</Link>:row[effectivePresentation.TitleField||'title']||row.name}</h3></CardTitle>}{effectivePresentation.MetaFields?.length?<CardDescription className="flex flex-wrap gap-2">{effectivePresentation.MetaFields.map(field=><span key={field}>{String(row[field]??'')}</span>)}</CardDescription>:null}</CardHeader><CardContent><ViewBody row={row} view={name} page={path} block={block} display={pageDisplay} field={effectivePresentation.BodyField||'body'} rich={formattedFields.includes(effectivePresentation.BodyField||'body')} file={fileFields.includes(effectivePresentation.BodyField||'body')}/></CardContent></Card>)}{mode!=='detail'&&display?.Pager?.Type!=='none'&&<Pagination previousDisabled={cursors.length===1} nextDisabled={!result.data.nextCursor} previous={()=>setCursors(value=>value.slice(0,-1))} next={()=>setCursors(value=>[...value,result.data.nextCursor])}/>}</div>}
	const applyControls=(event:FormEvent)=>{event.preventDefault();const next=new URLSearchParams(urlParams);for(const control of controls){const name=parameter(control.Filter);const original=urlParams.get(name)??String(control.Default??'');next.set(name,controlQueryValue(controlValues[control.Filter]??'',filters[control.Filter],original))}setCursors(['']);setURLParams(next,{replace:true})}
	return <div className="space-y-4">{pageDisplay?<PageHeader title={resolvedTitle||display?.Title?.Fallback||humanize(name)} description={display?.Description}/>:display&&resolvedTitle?<h2 className="font-heading text-2xl font-semibold">{resolvedTitle}</h2>:null}{Object.keys(displays).length>1?<Field id={'display-'+block} label="Display"><NativeSelect id={'display-'+block} value={activeDisplayName} onChange={event=>{const next=new URLSearchParams(urlParams);next.set(displayParameter,event.target.value);setCursors(['']);setURLParams(next,{replace:true})}}>{Object.keys(displays).sort().map(name=><NativeSelectOption key={name} value={name}>{humanize(name)}</NativeSelectOption>)}</NativeSelect></Field>:null}{controls.length?<form className="grid items-end gap-4 sm:grid-cols-2 lg:flex lg:flex-wrap" onSubmit={applyControls}>{controls.map(control=><ViewFilterControl key={control.Filter} scope={block} control={control} filter={filters[control.Filter]} value={controlValues[control.Filter]??''} onChange={value=>setControlValues(current=>({...current,[control.Filter]:value}))}/>)}<Button type="submit">Apply</Button></form>:null}{(searchFields.length||effectivePresentation.SearchFields?.length)?<form className="flex gap-2" role="search" onSubmit={event=>{event.preventDefault();setCursors(['']);setSubmittedSearch(search)}}><Input aria-label={'Search '+name.replaceAll('_',' ')} type="search" value={search} onChange={event=>setSearch(event.target.value)}/><Button type="submit">Search</Button></form>:null}{content}{mode==='table'&&display?.Pager?.Type!=='none'&&result.data&&<Pagination previousDisabled={cursors.length===1} nextDisabled={!result.data.nextCursor} previous={()=>setCursors(value=>value.slice(0,-1))} next={()=>setCursors(value=>[...value,result.data.nextCursor])}/>}</div>
}

function TableView({rows,fields,fieldTypes,display}:{rows:Row[];fields:NonNullable<ViewDisplay['Renderer']['Fields']>;fieldTypes:Record<string,string>;display?:ViewDisplay}){const selectable=Boolean(display?.Actions?.length)&&display?.Selection!=='none';const[selected,setSelected]=useState<string[]>([]);const visibleIDs=rows.map((row,index)=>String(row.id??index));const visibleSignature=JSON.stringify(visibleIDs);const visibleSelected=selected.filter(id=>visibleIDs.includes(id));useEffect(()=>{const visible=new Set<string>(JSON.parse(visibleSignature));setSelected(current=>current.filter(id=>visible.has(id)))},[visibleSignature]);const toggle=(id:string,checked:boolean)=>setSelected(current=>checked?(display?.Selection==='single'?[id]:[...current.filter(value=>value!==id),id]):current.filter(value=>value!==id));return <div className="space-y-4"><Table><TableHeader><TableRow>{selectable&&<TableHead scope="col">Select</TableHead>}{fields.map(column=><TableHead scope="col" key={column.Field}>{column.Label||humanize(column.Field)}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row,index)=>{const id=String(row.id??index);return <TableRow key={id}>{selectable&&<TableCell><Checkbox aria-label={'Select '+String(row[fields[0]?.Field]??id)} checked={visibleSelected.includes(id)} onCheckedChange={checked=>toggle(id,Boolean(checked))}/></TableCell>}{fields.map(column=><TableCell key={column.Field}>{column.LinkRoute?<Link className="font-medium text-primary hover:underline" to={viewLink(column.LinkRoute,row)}>{displayValue(row[column.Field],fieldTypes[column.Field])}</Link>:displayValue(row[column.Field],fieldTypes[column.Field])}</TableCell>)}</TableRow>})}</TableBody></Table>{selectable&&visibleSelected.length>0?<RecordActions names={display?.Actions||[]} ids={visibleSelected} onDone={()=>setSelected([])}/>:null}</div>}
function RecordActions({names,ids,onDone}:{names:string[];ids:string[];onDone:()=>void}){const qc=useQueryClient();const manifest=useQuery({queryKey:['manifest'],queryFn:()=>api<Manifest>('/api/system/manifest')});const[name,setName]=useState(names[0]||'');const[values,setValues]=useState<Row>({});const[result,setResult]=useState('');const[confirmOpen,setConfirmOpen]=useState(false);const batch=useRef<{signature:string;key:string}|undefined>(undefined);const action=manifest.data?.actions?.[name];const metadataPending=manifest.isFetching||Boolean(manifest.error)||!action;const run=useMutation({mutationFn:({input,key}:{input:Row;key:string})=>runActionBatch(name,ids,input,key),onSuccess:output=>{const succeeded=output.results.filter(item=>item.ok).length;const failed=output.results.length-succeeded;setResult(`${succeeded} succeeded, ${failed} failed.`);setConfirmOpen(false);void qc.invalidateQueries({queryKey:['public-view']});if(!failed)onDone()}});const execute=()=>{const input=recordActionValues(action,values);const signature=JSON.stringify({name,ids,input});if(batch.current?.signature!==signature)batch.current={signature,key:globalThis.crypto.randomUUID()};run.mutate({input,key:batch.current.key})};const submit=(event:FormEvent)=>{event.preventDefault();if(metadataPending)return;if(action.Confirm)setConfirmOpen(true);else execute()};return <form className="space-y-3 rounded-lg border p-4" onSubmit={submit}><div className="grid gap-3 sm:grid-cols-2"><Field id="record-action" label="Action"><NativeSelect id="record-action" value={name} onChange={event=>{setName(event.target.value);setValues({});setConfirmOpen(false);run.reset()}}>{names.map(value=><NativeSelectOption key={value} value={value}>{humanize(value)}</NativeSelectOption>)}</NativeSelect></Field>{action&&Object.entries(action.Input).filter(([field])=>field!=='id'&&!action.Derive?.[field]).map(([field,definition])=><RecordActionInput key={field} name={field} definition={definition} value={values[field]} onChange={value=>setValues(current=>({...current,[field]:value}))}/>)}</div><Button type="submit" disabled={run.isPending||metadataPending}>{run.isPending?'Running…':metadataPending?'Loading Action…':`Run for ${ids.length}`}</Button>{run.error&&!confirmOpen&&<ErrorAlert error={run.error}/>} {result&&<StatusAlert>{result}</StatusAlert>}<AlertDialog open={confirmOpen} onOpenChange={open=>{if(!run.isPending)setConfirmOpen(open)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Confirm action</AlertDialogTitle><AlertDialogDescription>{action?.Confirm}</AlertDialogDescription></AlertDialogHeader>{run.error&&<ErrorAlert error={run.error}/>}<AlertDialogFooter><AlertDialogCancel disabled={run.isPending}>Cancel</AlertDialogCancel><AlertDialogAction disabled={run.isPending||metadataPending} onClick={event=>{event.preventDefault();if(!metadataPending)execute()}}>Confirm</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></form>}
function recordActionValues(action:import('./api').Action|undefined,values:Row){const result={...values};if(!action)return result;for(const[field,definition]of Object.entries(action.Input)){if(field==='id'||action.Derive?.[field])continue;if(definition.Type==='boolean'&&definition.Required&&!Object.hasOwn(result,field))result[field]=false;if(definition.Type==='datetime'&&typeof result[field]==='string'&&result[field])result[field]=controlQueryValue(result[field],{Type:'datetime'})}return result}
function RecordActionInput({name,definition,value,onChange}:{name:string;definition:import('./api').Field;value:any;onChange:(value:any)=>void}){const id='record-action-'+name;const label=definition.Label||humanize(name);if(definition.Type==='password'||definition.Sensitive)return <Field id={id} label={label}><Input id={id} type="password" required={definition.Required} value={String(value??'')} onChange={event=>onChange(event.target.value)}/></Field>;if(definition.Type==='enum')return <Field id={id} label={label}><NativeSelect id={id} required={definition.Required} value={String(value??'')} onChange={event=>onChange(event.target.value)}><NativeSelectOption value="">Select</NativeSelectOption>{definition.Options?.map(option=><NativeSelectOption value={option} key={option}>{humanize(option)}</NativeSelectOption>)}</NativeSelect></Field>;if(definition.Type==='boolean')return <div className="flex items-center gap-2"><Checkbox id={id} checked={Boolean(value)} onCheckedChange={checked=>onChange(Boolean(checked))}/><Label htmlFor={id}>{label}</Label></div>;const numeric=['integer','money'].includes(definition.Type);const numberInput=numeric||definition.Type==='decimal';const type=numberInput?'number':definition.Type==='date'?'date':definition.Type==='datetime'?'datetime-local':definition.Type==='email'?'email':'text';return <Field id={id} label={label}><Input id={id} type={type} step={definition.Type==='decimal'?'any':undefined} required={definition.Required} value={String(value??'')} onChange={event=>onChange(numeric?(event.target.value===''?'':Number(event.target.value)):event.target.value)}/></Field>}
function displayValue(value:any,type?:string){if(value===null||value===undefined)return '';if(type==='boolean'||typeof value==='boolean')return value?'Yes':'No';if(type==='date'||type==='datetime')return formatDemoDate(value);if(type==='integer'||type==='decimal'||type==='money')return new Intl.NumberFormat().format(Number(value));if(typeof value==='object')return JSON.stringify(value);return String(value)}
function ViewFilterControl({scope,control,filter,value,onChange}:{scope:string;control:NonNullable<ViewDisplay['Controls']>[number];filter?:ViewFilter;value:string;onChange:(value:string)=>void}){const id='view-filter-'+scope+'-'+control.Filter;const label=control.Label||filter?.Label||humanize(control.Filter);const widget=control.Widget==='auto'||!control.Widget?(filter?.Type==='enum'?'select':filter?.Type==='boolean'?'checkbox':filter?.Type==='integer'||filter?.Type==='decimal'||filter?.Type==='money'?'number':filter?.Type==='date'||filter?.Type==='datetime'?'date':'text'):control.Widget;if(widget==='select')return <Field id={id} label={label}><NativeSelect id={id} value={value} onChange={event=>onChange(event.target.value)}><NativeSelectOption value="">All</NativeSelectOption>{filter?.Options?.map(option=><NativeSelectOption key={option} value={option}>{humanize(option)}</NativeSelectOption>)}</NativeSelect></Field>;if(widget==='checkbox')return <div className="flex items-center gap-2"><Checkbox id={id} checked={value==='true'} onCheckedChange={checked=>onChange(checked?'true':'false')}/><Label htmlFor={id}>{label}</Label></div>;const type=widget==='number'?'number':widget==='date'&&filter?.Type==='datetime'?'datetime-local':widget==='date'?'date':'text';return <Field id={id} label={label}><Input id={id} type={type} step={filter?.Type==='decimal'?'any':type==='datetime-local'?'1':undefined} value={value} onChange={event=>onChange(event.target.value)}/></Field>}
export function controlInputValue(value:string,filter?:ViewFilter){if(!value||filter?.Type!=='datetime')return value;const date=new Date(value);if(Number.isNaN(date.valueOf()))return value;return new Date(date.valueOf()-date.getTimezoneOffset()*60_000).toISOString().slice(0,19)}
export function controlQueryValue(value:string,filter?:ViewFilter,original=''){if(!value||filter?.Type!=='datetime')return value;if(original&&controlInputValue(original,filter)===value)return original;const date=new Date(value);return Number.isNaN(date.valueOf())?value:date.toISOString()}

function drillLink(drill:ViewDrill|undefined,row:Row,filters:Record<string,string>){if(!drill?.Route)return'';const query=new URLSearchParams();for(const binding of drill.Bindings||[]){const value=binding.Source==='group'?row[binding.Name]:filters[binding.Name];if(binding.Source==='group'&&(value===undefined||value===null||value===''))return'';if(value!==undefined&&value!==null&&value!=='')query.set(binding.Filter,String(value))}return drill.Route+(query.size?'?'+query:'')}
function MetricView({row,presentation,drill,filters}:{row:Row;presentation:ViewPresentation;drill?:ViewDrill;filters:Record<string,string>}){const value=row[presentation.MetricField||''];if(value===null||value===undefined)return <Card><CardContent className="py-8 text-center text-muted-foreground">{presentation.EmptyState||'Nothing to show.'}</CardContent></Card>;const content=<Card><CardHeader><CardDescription>{presentation.MetricLabel||humanize(presentation.MetricField||'metric')}</CardDescription><CardTitle><span className="text-4xl" data-testid="metric-value">{String(value)}</span></CardTitle></CardHeader></Card>;const href=drillLink(drill,row,filters);return href?<Link aria-label={'Open '+(presentation.MetricLabel||'metric')+' records'} to={href}>{content}</Link>:content}
function ChartView({rows,presentation,drill,filters}:{rows:Row[];presentation:ViewPresentation;drill?:ViewDrill;filters:Record<string,string>}){const values=rows.map(row=>{const value=row[presentation.MetricField||''];return value===null||value===undefined?null:Number(value)});const maximum=Math.max(...values.filter((value):value is number=>value!==null).map(value=>Math.abs(value)),1);return <div className="space-y-3" role="img" aria-label={presentation.MetricLabel||'Bar chart'} data-testid="bar-chart">{rows.map((row,index)=>{const label=String(row[presentation.GroupField||'']??'Unknown');const value=values[index];const bar=<div className="grid grid-cols-[minmax(6rem,1fr)_3fr_auto] items-center gap-3"><span>{label}</span><div className="h-5 rounded bg-muted"><div className={`h-5 rounded ${value!==null&&value<0?'bg-destructive':'bg-primary'}`} style={{width:`${value===null?0:Math.abs(value)/maximum*100}%`}}/></div><span aria-label={`${label}: ${value===null?'No value':value}`}>{value===null?'—':value}</span></div>;const href=value===null?'':drillLink(drill,row,filters);return href?<Link key={label} aria-label={`Open ${label} records`} to={href}>{bar}</Link>:<div key={label}>{bar}</div>})}</div>}
function CalendarView({rows,presentation}:{rows:Row[];presentation:ViewPresentation}){return <ol className="grid gap-3 sm:grid-cols-2" data-testid="calendar-view">{[...rows].sort((a,b)=>String(a[presentation.TimeField||'']).localeCompare(String(b[presentation.TimeField||'']))).map(row=>{const start=formatDemoDate(row[presentation.TimeField||'']);const end=presentation.EndField?formatDemoDate(row[presentation.EndField]):'';return <li key={String(row.id)}><Card><CardHeader><CardTitle>{row[presentation.TitleField||'title']||row.id}</CardTitle><CardDescription>{start}{end?' – '+end:''}</CardDescription></CardHeader></Card></li>})}</ol>}
function TimelineView({rows,presentation}:{rows:Row[];presentation:ViewPresentation}){return <ol className="relative space-y-6 border-l pl-6" data-testid="timeline-view">{rows.map(row=><li key={String(row.id)+JSON.stringify(row)}><span className="absolute -ml-[1.85rem] mt-1.5 size-3 rounded-full bg-primary"/><time className="text-sm text-muted-foreground">{formatDemoDate(row[presentation.TimeField||''])}</time><h3 className="font-semibold">{presentation.LinkRoute?<Link className="hover:underline" to={viewLink(presentation.LinkRoute,row)}>{row[presentation.TitleField||'title']}</Link>:row[presentation.TitleField||'title']}</h3>{presentation.BodyField?<p>{String(row[presentation.BodyField]??'')}</p>:null}{presentation.MetaFields?.length?<p className="text-sm text-muted-foreground">{presentation.MetaFields.map(field=>String(row[field]??'')).filter(Boolean).join(' · ')}</p>:null}</li>)}</ol>}
function formatDemoDate(value:any){const date=new Date(String(value));return Number.isNaN(date.valueOf())?String(value??''):new Intl.DateTimeFormat('en-US',{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'}).format(date)}

function mergeDetail(rows:Row[],meta:string[]){const result={...rows[0]};for(const field of meta){const values=[...new Set(rows.map(row=>row[field]).filter(value=>value!==null&&value!==undefined&&value!==''))];result[field]=values.join(', ')}return result}
function ViewBody({row,view,page,block,display,field,rich,file}:{row:Row;view:string;page:string;block:string;display:boolean;field:string;rich:boolean;file:boolean}){const selected=row[field];const value=String(selected??row.excerpt??row.description??'');if(file&&selected){const query=new URLSearchParams({view,_page:page});query.set(display?'_display':'_block',block);return <Button variant="outline" asChild><a href={'/api/files/'+encodeURIComponent(String(selected))+'?'+query}>Download attachment</a></Button>}return rich&&selected!==null&&selected!==undefined?<div className="rich-text" dangerouslySetInnerHTML={{__html:String(selected)}}/>:<p className="leading-7">{value}</p>}
function viewLink(template:string,row:Row){return template.replace(/:([a-zA-Z0-9_.]+)/g,(_,field)=>encodeURIComponent(String(row[field]??'')))}

function BoardView({rows,presentation}:{rows:Row[];presentation:ViewPresentation}){
  const queryClient=useQueryClient();const manifest=useQuery({queryKey:['manifest'],queryFn:()=>api<Manifest>('/api/system/manifest')})
  const move=useMutation({mutationFn:({id,status}:{id:string;status:string})=>callAction(presentation.MoveAction||'',{id,[presentation.GroupField||'status']:status}),onSuccess:()=>void queryClient.invalidateQueries({queryKey:['public-view']})})
  const columns=presentation.Columns||[];const group=presentation.GroupField||'status';const title=presentation.TitleField||'title';const order=presentation.OrderField;const action=manifest.data?.actions?.[presentation.MoveAction||''];const transitions=action?.Transitions??(action?.Lifecycle?manifest.data?.lifecycles?.[action.Lifecycle]?.Transitions:undefined)??{}
  return <div className="overflow-x-auto"><div className="grid min-w-[48rem] gap-4" style={{gridTemplateColumns:`repeat(${columns.length}, minmax(15rem, 1fr))`}}>{columns.map(column=><section className="rounded-xl bg-muted/60 p-3" key={column}><h3 className="mb-3 font-semibold">{humanize(column)}</h3><div className="space-y-3">{rows.filter(row=>row[group]===column).sort((a,b)=>order?Number(a[order]??0)-Number(b[order]??0):0).map(row=>{const current=String(row[group]);const allowed=new Set([current,...(transitions[current]||[])]);const targets=columns.filter(value=>allowed.has(value));return <Card key={row.id}><CardHeader><CardTitle>{presentation.LinkRoute?<Link className="hover:underline" to={viewLink(presentation.LinkRoute,row)}>{row[title]}</Link>:row[title]}</CardTitle>{presentation.MetaFields?.length?<CardDescription>{presentation.MetaFields.map(field=>String(row[field]??'')).filter(Boolean).join(' · ')}</CardDescription>:null}</CardHeader><CardContent className="space-y-3"><p>{String(row[presentation.BodyField||'description']??'')}</p><Field id={'move-'+row.id} label="Status"><NativeSelect id={'move-'+row.id} aria-label={'Status for '+row[title]} value={current} disabled={move.isPending||targets.length===1} onChange={event=>move.mutate({id:String(row.id),status:event.target.value})}>{targets.map(value=><NativeSelectOption key={value} value={value}>{humanize(value)}</NativeSelectOption>)}</NativeSelect></Field></CardContent></Card>})}{!rows.some(row=>row[group]===column)&&<p className="text-sm text-muted-foreground">No tasks</p>}</div></section>)}</div>{move.error&&<ErrorAlert error={move.error}/>}</div>
}

function TreeView({rows,presentation}:{rows:Row[];presentation:ViewPresentation}){
  const parent= presentation.ParentField||'parent_id';const order=presentation.OrderField;const ids=new Set(rows.map(row=>String(row.id)))
  const[collapsed,setCollapsed]=useState<Set<string>>(new Set())
  const children=new Map<string,Row[]>();const roots:Row[]=[]
  for(const row of rows){const parentID=String(row[parent]??'');if(!parentID||!ids.has(parentID))roots.push(row);else children.set(parentID,[...(children.get(parentID)||[]),row])}
  const reachable=new Set<string>();const mark=(seed:Row)=>{const queue=[seed];while(queue.length){const current=queue.shift()!;const id=String(current.id);if(reachable.has(id))continue;reachable.add(id);queue.push(...(children.get(id)||[]))}}
  roots.forEach(mark);for(const row of rows)if(!reachable.has(String(row.id))){roots.push(row);mark(row)}
  const sort=(items:Row[])=>items.sort((a,b)=>order?Number(a[order]||0)-Number(b[order]||0):String(a[presentation.TitleField||'title']).localeCompare(String(b[presentation.TitleField||'title'])))
  const branch=(row:Row,depth:number,path:Set<string>):React.ReactNode=>{const id=String(row.id);if(path.has(id))return <li className="text-destructive" key={id}>Invalid hierarchy cycle at {id}</li>;const descendants=sort([...(children.get(id)||[])]);const next=new Set(path).add(id);return <li key={id}><div className="flex items-center gap-2 border-b py-2" style={{paddingLeft:`${Math.min(depth,12)*1.25}rem`}}>{descendants.length?<Button size="sm" variant="ghost" aria-label={(collapsed.has(id)?'Expand ':'Collapse ')+String(row[presentation.TitleField||'title'])} onClick={()=>setCollapsed(current=>{const value=new Set(current);if(value.has(id))value.delete(id);else value.add(id);return value})}>{collapsed.has(id)?'›':'⌄'}</Button>:<span className="inline-block w-8"/>}{presentation.LinkRoute?<Link className="font-medium text-primary hover:underline" to={viewLink(presentation.LinkRoute,row)}>{row[presentation.TitleField||'title']}</Link>:<span>{row[presentation.TitleField||'title']}</span>}{presentation.MetaFields?.map(field=><span className="text-sm text-muted-foreground" key={field}>{String(row[field]??'')}</span>)}</div>{!collapsed.has(id)&&descendants.length>0&&<ul>{descendants.map(child=>branch(child,depth+1,next))}</ul>}</li>}
  return <ul className="rounded-xl border" data-testid="tree-view">{sort(roots).map(row=>branch(row,0,new Set()))}</ul>
}

type WebformBlockProps={name:string;block:string;renderedForm?:Manifest['webforms'][string]}
function WebformBlock(props:WebformBlockProps){
  const path=useLocation().pathname
  return <WebformBlockPage key={`${props.name}:${props.block}:${path}`} {...props} path={path}/>
}
function WebformBlockPage({name,block,renderedForm,path}:WebformBlockProps&{path:string}){
  const manifest=useQuery({queryKey:['manifest'],queryFn:()=>api<Manifest>('/api/system/manifest'),enabled:!renderedForm});const form=renderedForm||manifest.data?.webforms?.[name]
  const[values,setValues]=useState<Row>({});const[step,setStep]=useState(0);const[done,setDone]=useState('')
  const query=new URLSearchParams({_page:path,_block:block})
  const submit=useMutation({mutationFn:()=>api<{confirmation:string}>('/api/webforms/'+name+'/submit?'+query,{method:'POST',body:formBody(form,values)}),onSuccess:result=>setDone(result.confirmation)})
  if(!form)return null
  if(done)return <StatusAlert>{done}</StatusAlert>
  const names=form.Steps?.[step]
  const elements=(names?form.Elements.filter(element=>names.includes(element.Name)):form.Elements).filter(element=>evaluate(element.Visible,values))
  return <SectionCard><form className="space-y-4" onSubmit={event=>{event.preventDefault();if(form.Steps&&step<form.Steps.length-1)setStep(step+1);else submit.mutate()}}>{elements.map(element=><FormField key={element.Name} element={{...element,Required:element.Required||(element.RequiredWhen?evaluate(element.RequiredWhen,values):false)}} value={values[element.Name]} error={(submit.error as APIError|undefined)?.fields?.[element.Name]} onChange={value=>setValues(current=>({...current,[element.Name]:value}))}/>)}{submit.error&&<ErrorAlert error={submit.error}/>}<Button type="submit" disabled={submit.isPending}>{form.Steps&&step<form.Steps.length-1?'Next':submit.isPending?'Submitting…':'Submit'}</Button></form></SectionCard>
}

function formBody(form:Manifest['webforms'][string]|undefined,values:Row):BodyInit{
  return encodeInput(values,(form?.Elements||[]).some(element=>element.Type==='file'))
}

export function evaluate(expression:import('./api').Expression|undefined|null,values:Row):boolean{
  if(!expression)return true
  const args=expression.Args||[]
  if(expression.Op==='and')return args.every(item=>evaluate(item,values))
  if(expression.Op==='or')return args.some(item=>evaluate(item,values))
  if(expression.Op==='not'){if(args.length!==1)throw new Error('not requires one argument');return !evaluate(args[0],values)}
  const resolve=(value:typeof expression.Left)=>{if(!value)throw new Error('expression value is missing');if(value.Source==='input')return values[value.Name||''];if(value.Source==='literal')return value.Literal;throw new Error('unsupported client value source '+value.Source)}
  const left=resolve(expression.Left)
  if(expression.Op==='is_null')return left==null
  if(expression.Op==='is_not_null')return left!=null
  const right=resolve(expression.Right)
  if(expression.Op==='eq')return left===right
  if(expression.Op==='ne')return left!==right
  if(expression.Op==='gt'||expression.Op==='gte'||expression.Op==='lt'||expression.Op==='lte'){
    const inputPending=(value:typeof expression.Left)=>value?.Source==='input'&&!Object.prototype.hasOwnProperty.call(values,value.Name||'')
    const leftPending=inputPending(expression.Left),rightPending=inputPending(expression.Right)
    if((!leftPending&&typeof left!=='number')||(!rightPending&&typeof right!=='number'))throw new Error('comparison requires numbers')
    if(leftPending||rightPending)return false
    if(expression.Op==='gt')return left>right;if(expression.Op==='gte')return left>=right;if(expression.Op==='lt')return left<right;return left<=right
  }
  if(expression.Op==='in'||expression.Op==='not_in'){if(!Array.isArray(right))throw new Error(expression.Op+' requires a list');const included=right.some(value=>Object.is(value,left));return expression.Op==='in'?included:!included}
  if(expression.Op==='contains')return String(left).includes(String(right))
  if(expression.Op==='starts_with')return String(left).startsWith(String(right))
  if(expression.Op==='ends_with')return String(left).endsWith(String(right))
  throw new Error('unsupported client expression operator '+expression.Op)
}

function FormField({element,value,error,onChange}:{element:FormElement;value:any;error?:string;onChange:(value:any)=>void}){
  if(element.Type==='group')return <SectionCard title={humanize(element.Name)}><div className="space-y-4"><Button type="button" variant="outline" onClick={()=>onChange([...(value||[]),{}])}>Add</Button>{(value||[]).map((row:Row,index:number)=><div className="grid gap-4 rounded-lg border p-4 sm:grid-cols-2" key={index}>{element.Children?.map(child=><FormField key={child.Name} element={child} value={row[child.Name]} onChange={next=>{const rows=[...value];rows[index]={...row,[child.Name]:next};onChange(rows)}}/>)}</div>)}</div></SectionCard>
  const id='form-'+element.Name;const label=element.Name.replaceAll('_',' ')
  if(element.Type==='textarea')return <Field id={id} label={label} error={error}><Textarea id={id} required={element.Required} value={value??''} onChange={event=>onChange(event.target.value)}/></Field>
  if(element.Type==='file')return <Field id={id} label={label} error={error}><Input id={id} type="file" required={element.Required} onChange={event=>onChange(event.target.files?.[0])}/></Field>
  if(element.Type==='select'||element.Type==='entity reference')return <Field id={id} label={label} error={error}><NativeSelect id={id} required={element.Required} value={value??''} onChange={event=>onChange(event.target.value)}><NativeSelectOption value=""/>{element.Options?.map(option=><NativeSelectOption key={option}>{option}</NativeSelectOption>)}</NativeSelect></Field>
  if(element.Type==='checkbox')return <div className="grid gap-2"><div className="flex items-center gap-2"><Checkbox id={id} checked={Boolean(value)} onCheckedChange={checked=>onChange(Boolean(checked))}/><Label htmlFor={id}>{label}</Label></div>{error&&<p className="text-sm text-destructive" role="alert">{error}</p>}</div>
  const type=element.Type==='email'?'email':element.Type==='password'?'password':element.Type==='number'||element.Type==='integer'?'number':element.Type==='date'?'date':element.Type==='datetime'?'datetime-local':'text'
  return <Field id={id} label={label} error={error}><Input id={id} type={type} required={element.Required} value={value??''} onChange={event=>onChange(element.Type==='number'||element.Type==='integer'?Number(event.target.value):event.target.value)}/></Field>
}

function ActionBlock({name}:{name:string}){const mutation=useMutation({mutationFn:()=>callAction(name,{})});return <div className="space-y-3"><Button onClick={()=>mutation.mutate()} disabled={mutation.isPending}>{humanize(name)}</Button>{mutation.error&&<ErrorAlert error={mutation.error}/>}</div>}
function MenuBlock({items}:{items:Array<{Route:string;Label:string}>}){return <nav className="flex flex-wrap gap-2" aria-label="Page navigation">{items.map(item=><Button key={item.Route} variant="outline" asChild><Link to={item.Route}>{item.Label}</Link></Button>)}</nav>}
function Pagination({previousDisabled,nextDisabled,previous,next}:{previousDisabled:boolean;nextDisabled:boolean;previous:()=>void;next:()=>void}){return <nav className="flex justify-end gap-2" aria-label="Pagination"><Button variant="outline" disabled={previousDisabled} onClick={previous}>Previous</Button><Button variant="outline" disabled={nextDisabled} onClick={next}>Next</Button></nav>}
function humanize(value:string){return value.replaceAll('_',' ').replace(/^./,letter=>letter.toUpperCase())}

type PageResult={tree:Node}
function loadPage(path:string,search:string){const query=new URLSearchParams(search);query.set('path',path);return api<PageResult>('/api/system/page?'+query)}
function Public(){
  const loc=useLocation();const pageKey=loc.search?['page',loc.pathname,loc.search]:['page',loc.pathname];const result=useQuery({queryKey:pageKey,queryFn:()=>loadPage(loc.pathname,loc.search),placeholderData:(previous,query)=>query?.queryKey[1]===loc.pathname?previous:undefined})
  if(result.isPending)return <Shell><Page><LoadingState/></Page></Shell>
  if(result.error)return <Shell><Page><PageHeader title="Bean" description="Metadata-driven applications, compiled."/></Page></Shell>
  if(result.data.tree.component==='Sequence')return <Shell chrome={false}><Renderer node={result.data.tree}/></Shell>
  return <Shell><Page className="space-y-6"><Renderer node={result.data.tree}/></Page></Shell>
}

export default function App(){const loc=useLocation();const currentPath=useRef(loc.pathname);currentPath.current=loc.pathname;return <CurrentPath.Provider value={currentPath}><Routes><Route path="/login" element={<Login/>}/><Route path="/explore" element={<Shell><Explore/></Shell>}/><Route path="/studio" element={<Shell><Studio/></Shell>}/><Route path="/admin/*" element={<Shell><Admin/></Shell>}/><Route path="*" element={<Public/>}/></Routes></CurrentPath.Provider>}
