import {useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {api} from './api'
import {useEditor} from './store'
import './studio.css'

type Definition={apiVersion:string;kind:string;metadata:{name:string;namespace?:string};spec:Record<string,any>}
type FieldSpec={name:string;label?:string;type:string;required?:boolean;unique?:boolean;options?:string[];relation?:{entity:string;kind:string;targetField?:string}}
const coreKinds=['Entity','View','Action','Policy','AdminResource']
const allKinds=[...coreKinds,'Webform','Block','Panel','Page','Role','Menu','Job']

export function Studio(){
  const editor=useEditor();const qc=useQueryClient();const[advanced,setAdvanced]=useState(false)
  const defs=useQuery({queryKey:['definitions'],queryFn:()=>api<Definition[]>('/api/admin/definitions')})
  const releases=useQuery({queryKey:['releases'],queryFn:()=>api<any[]>('/api/admin/releases')})
  const spec=parseSpec(editor.spec)
  const save=useMutation({mutationFn:()=>api('/api/admin/definitions',{method:'POST',body:JSON.stringify({apiVersion:'bean/v1alpha1',kind:editor.kind,metadata:{namespace:'default',name:editor.name},spec:parseStrict(editor.spec)})}),onSuccess:()=>{editor.reset();setAdvanced(false);void qc.invalidateQueries({queryKey:['definitions']})}})
  const validate=useMutation({mutationFn:()=>api<any>('/api/admin/releases/validate',{method:'POST'})})
  const publish=useMutation({mutationFn:()=>api<any>('/api/admin/releases/publish',{method:'POST'}),onSuccess:()=>{void qc.invalidateQueries({queryKey:['releases']})}})
  function update(next:Record<string,any>){editor.set({spec:JSON.stringify(next,null,2)})}
  function chooseKind(kind:string){editor.set({kind,spec:'{}'});setAdvanced(!coreKinds.includes(kind))}
  function load(definition:Definition){editor.set({kind:definition.kind,name:definition.metadata.name,spec:JSON.stringify(definition.spec,null,2)});setAdvanced(!coreKinds.includes(definition.kind))}
  return <main><h1>Studio</h1><section><h2>Definition editor</h2><label>Kind<select data-testid="definition-kind" value={editor.kind} onChange={event=>chooseKind(event.target.value)}>{allKinds.map(kind=><option key={kind}>{kind}</option>)}</select></label><label>Machine name<input data-testid="definition-name" required pattern="[a-z][a-z0-9_]*" value={editor.name} onChange={event=>editor.set({name:event.target.value})}/></label>{coreKinds.includes(editor.kind)&&!advanced&&<VisualEditor kind={editor.kind} spec={spec} definitions={defs.data||[]} update={update}/>}<label className="checkbox"><input type="checkbox" checked={advanced} onChange={event=>setAdvanced(event.target.checked)}/>Advanced JSON</label>{advanced&&<label>Specification JSON<textarea data-testid="definition-spec" rows={16} value={editor.spec} onChange={event=>editor.set({spec:event.target.value})}/></label>}<button data-testid="save-definition" disabled={!editor.name||save.isPending} onClick={()=>save.mutate()}>Save draft</button>{save.error&&<p role="alert">{save.error.message}</p>}</section><section><h2>Release preview</h2><button data-testid="validate-release" onClick={()=>validate.mutate()}>Validate and preview</button><button data-testid="publish-release" onClick={()=>publish.mutate()}>Publish</button>{validate.data?.migration&&<div><h3>Migration</h3>{validate.data.migration.Descriptions?.length?<ul>{validate.data.migration.Descriptions.map((item:string)=><li key={item}>{item}</li>)}</ul>:<p>No schema changes.</p>}<p>Release {Number(releases.data?.[0]?.version||0)+1}</p></div>}<pre data-testid="diagnostics">{JSON.stringify(publish.data||validate.data||{},null,2)}</pre><p>Active release: {releases.data?.[0]?.id||'none'}</p></section><section><h2>Definitions</h2><ul>{defs.data?.map(definition=><li key={definition.kind+'/'+definition.metadata.name}><button className="definition-link" onClick={()=>load(definition)}>{definition.kind}: {definition.metadata.name}</button></li>)}</ul></section></main>
}

function VisualEditor({kind,spec,definitions,update}:{kind:string;spec:Record<string,any>;definitions:Definition[];update:(next:Record<string,any>)=>void}){
  if(kind==='Entity')return <EntityEditor spec={spec} definitions={definitions} update={update}/>
  if(kind==='View')return <ViewEditor spec={spec} definitions={definitions} update={update}/>
  if(kind==='Action')return <ActionEditor spec={spec} definitions={definitions} update={update}/>
  if(kind==='Policy')return <PolicyEditor spec={spec} update={update}/>
  return <AdminResourceEditor spec={spec} definitions={definitions} update={update}/>
}

function EntityEditor({spec,definitions,update}:{spec:Record<string,any>;definitions:Definition[];update:(next:Record<string,any>)=>void}){
  const fields=(spec.fields||[]) as FieldSpec[];const entities=names(definitions,'Entity')
  function field(index:number,patch:Partial<FieldSpec>){const next=[...fields];next[index]={...next[index],...patch};update({...spec,fields:next})}
  return <fieldset><legend>Entity</legend><label>Label<input data-testid="entity-label" value={spec.label||''} onChange={event=>update({...spec,label:event.target.value})}/></label><div className="checkbox-row"><label className="checkbox"><input type="checkbox" checked={Boolean(spec.owner)} onChange={event=>update({...spec,owner:event.target.checked})}/>Owner scoped</label><label className="checkbox"><input type="checkbox" checked={Boolean(spec.tenant)} onChange={event=>update({...spec,tenant:event.target.checked})}/>Tenant scoped</label></div><h3>Fields</h3>{fields.map((item,index)=><div className="visual-row" data-testid="entity-field" key={index}><label>Name<input value={item.name||''} onChange={event=>field(index,{name:event.target.value})}/></label><label>Label<input value={item.label||''} onChange={event=>field(index,{label:event.target.value})}/></label><label>Type<select value={item.type||'string'} onChange={event=>field(index,{type:event.target.value,relation:event.target.value==='relation'?{entity:entities[0]||'',kind:'many-to-one',targetField:'id'}:undefined})}>{['string','text','richtext','integer','decimal','money','boolean','date','datetime','uuid','email','url','json','enum','relation'].map(type=><option key={type}>{type}</option>)}</select></label>{item.type==='enum'&&<label>Options<input value={(item.options||[]).join(', ')} onChange={event=>field(index,{options:csv(event.target.value)})}/></label>}{item.type==='relation'&&<><label>Related entity<select value={item.relation?.entity||''} onChange={event=>field(index,{relation:{entity:event.target.value,kind:item.relation?.kind||'many-to-one',targetField:'id'}})}><option value="">Select…</option>{entities.map(entity=><option key={entity}>{entity}</option>)}</select></label><label>Relation<select value={item.relation?.kind||'many-to-one'} onChange={event=>field(index,{relation:{entity:item.relation?.entity||'',kind:event.target.value,targetField:'id'}})}>{['many-to-one','one-to-one','one-to-many','many-to-many'].map(value=><option key={value}>{value}</option>)}</select></label></>}<label className="checkbox"><input type="checkbox" checked={Boolean(item.required)} onChange={event=>field(index,{required:event.target.checked})}/>Required</label><button className="danger secondary" onClick={()=>update({...spec,fields:fields.filter((_,candidate)=>candidate!==index)})}>Remove</button></div>)}<button data-testid="add-field" onClick={()=>update({...spec,fields:[...fields,{name:'',label:'',type:'string'}]})}>Add field</button></fieldset>
}

function ViewEditor({spec,definitions,update}:{spec:Record<string,any>;definitions:Definition[];update:(next:Record<string,any>)=>void}){const entity=entityDefinition(definitions,spec.entity);const fields=['id',...((entity?.spec.fields||[]) as FieldSpec[]).map(field=>field.name),'created_at','updated_at','version'];const selected=(spec.fields||[]) as string[];return <fieldset><legend>View</legend><Reference label="Entity" testId="view-entity" value={spec.entity||''} options={names(definitions,'Entity')} onChange={value=>update({...spec,entity:value,fields:['id']})}/><Reference label="Policy" value={spec.policy||''} options={names(definitions,'Policy')} optional onChange={value=>update({...spec,policy:value})}/><h3>Projection</h3><div className="choice-grid">{fields.map(name=><label className="checkbox" key={name}><input type="checkbox" checked={selected.includes(name)} onChange={event=>update({...spec,fields:event.target.checked?[...selected,name]:selected.filter(value=>value!==name)})}/>{name}</label>)}</div><label>Sort field<select value={spec.sort?.[0]?.field||''} onChange={event=>update({...spec,sort:event.target.value?[{field:event.target.value,desc:Boolean(spec.sort?.[0]?.desc)}]:[]})}><option value="">None</option>{selected.map(name=><option key={name}>{name}</option>)}</select></label><label className="checkbox"><input type="checkbox" checked={Boolean(spec.sort?.[0]?.desc)} onChange={event=>update({...spec,sort:spec.sort?.length?[{...spec.sort[0],desc:event.target.checked}]:[]})}/>Descending</label></fieldset>}

function ActionEditor({spec,definitions,update}:{spec:Record<string,any>;definitions:Definition[];update:(next:Record<string,any>)=>void}){const entity=entityDefinition(definitions,spec.entity);const fields=(entity?.spec.fields||[]) as FieldSpec[];const input=(spec.input||{}) as Record<string,any>;function toggle(field:FieldSpec,enabled:boolean){const next={...input};if(enabled)next[field.name]={type:field.type,required:field.required,options:field.options};else delete next[field.name];update({...spec,input:next})}return <fieldset><legend>Action</legend><Reference label="Entity" testId="action-entity" value={spec.entity||''} options={names(definitions,'Entity')} onChange={value=>update({...spec,entity:value,input:{}})}/><label>Operation<select data-testid="action-operation" value={spec.operation||'create'} onChange={event=>update({...spec,operation:event.target.value})}>{['create','update','delete','transition'].map(operation=><option key={operation}>{operation}</option>)}</select></label><Reference label="Policy" value={spec.policy||''} options={names(definitions,'Policy')} optional onChange={value=>update({...spec,policy:value})}/><h3>Inputs</h3><div className="choice-grid">{fields.map(field=><label className="checkbox" key={field.name}><input type="checkbox" checked={Boolean(input[field.name])} onChange={event=>toggle(field,event.target.checked)}/>{field.name}</label>)}</div></fieldset>}

function PolicyEditor({spec,update}:{spec:Record<string,any>;update:(next:Record<string,any>)=>void}){return <fieldset><legend>Policy</legend><label>Read roles<input data-testid="policy-read-roles" value={(spec.readRoles||[]).join(', ')} onChange={event=>update({...spec,readRoles:csv(event.target.value)})}/></label><label>Write roles<input data-testid="policy-write-roles" value={(spec.writeRoles||[]).join(', ')} onChange={event=>update({...spec,writeRoles:csv(event.target.value)})}/></label><div className="checkbox-row">{[['authenticated','Authenticated'],['owner','Owner scoped'],['tenant','Tenant scoped']].map(([key,label])=><label className="checkbox" key={key}><input type="checkbox" checked={Boolean(spec[key])} onChange={event=>update({...spec,[key]:event.target.checked})}/>{label}</label>)}</div></fieldset>}

function AdminResourceEditor({spec,definitions,update}:{spec:Record<string,any>;definitions:Definition[];update:(next:Record<string,any>)=>void}){const entity=entityDefinition(definitions,spec.entity);const fields=['id',...((entity?.spec.fields||[]) as FieldSpec[]).map(field=>field.name),'created_at','updated_at','version'];return <fieldset><legend>Admin resource</legend><Reference label="Entity" testId="admin-entity" value={spec.entity||''} options={names(definitions,'Entity')} onChange={value=>update({...spec,entity:value})}/><Reference label="View" value={spec.view||''} options={names(definitions,'View')} optional onChange={value=>update({...spec,view:value})}/><label>Description<input value={spec.description||''} onChange={event=>update({...spec,description:event.target.value})}/></label><label>Label field<select value={spec.labelField||''} onChange={event=>update({...spec,labelField:event.target.value})}><option value="">Automatic</option>{fields.map(field=><option key={field}>{field}</option>)}</select></label>{[['columns','List columns'],['search','Search fields'],['filters','Filter fields']].map(([key,label])=><label key={key}>{label}<select multiple value={spec.list?.[key]||[]} onChange={event=>update({...spec,list:{...spec.list,[key]:Array.from(event.target.selectedOptions,option=>option.value)}})}>{fields.map(field=><option key={field}>{field}</option>)}</select></label>)}<label>Form fields<select multiple value={spec.form?.fields||[]} onChange={event=>update({...spec,form:{...spec.form,fields:Array.from(event.target.selectedOptions,option=>option.value)}})}>{fields.filter(field=>!['id','created_at','updated_at','version'].includes(field)).map(field=><option key={field}>{field}</option>)}</select></label></fieldset>}

function Reference({label,value,options,onChange,optional=false,testId}:{label:string;value:string;options:string[];onChange:(value:string)=>void;optional?:boolean;testId?:string}){return <label>{label}<select data-testid={testId||'reference-'+label.toLowerCase()} required={!optional} value={value} onChange={event=>onChange(event.target.value)}>{optional&&<option value="">None</option>}{!optional&&<option value="">Select…</option>}{options.map(option=><option key={option}>{option}</option>)}</select></label>}
function names(definitions:Definition[],kind:string){return definitions.filter(definition=>definition.kind===kind).map(definition=>definition.metadata.name).sort()}
function entityDefinition(definitions:Definition[],name:string){return definitions.find(definition=>definition.kind==='Entity'&&definition.metadata.name===name)}
function parseSpec(value:string):Record<string,any>{try{return JSON.parse(value)}catch{return {}}}
function parseStrict(value:string):Record<string,any>{const parsed=JSON.parse(value);if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw new Error('Specification must be a JSON object.');return parsed}
function csv(value:string){return value.split(',').map(item=>item.trim()).filter(Boolean)}
